### ISSUE TITLE
PAC 自动模式，git 的 10022 端口操作卡在连接

### ISSUE THREAD

**Issue by fancyoung** [paradiseduo/ShadowsocksX-NG-R8#12]
最近终端用git提交更新代码总是卡住(自己的gitlab，10022端口)，发现是因为处于“PAC 自动模式”。
奇怪的是别的模式(白名单、全局、手动、ACL)都可以。

最近发生的，应该和软件本身无关。但想不通是什么原因(gfwlist?)会导致这个。

**Comment by paradiseduo** [comment]
可以修改自定义PAC，把IP加入白名单

**Comment by fancyoung** [comment]
已找到原因，是 osx 升级导致的。更新 openssh 解决。
https://www.v2ex.com/t/656281
