### ISSUE TITLE
Bug 服务器设置中列表无滚动条

### ISSUE THREAD

**Issue by xem1987** [paradiseduo/ShadowsocksX-NG-R8#13]
version: 1.6.0(1)
<img width="591" alt="图片" src="https://user-images.githubusercontent.com/5061622/79044875-73e8da00-7bf7-11ea-9331-e8b602081f56.png">

**Comment by paradiseduo** [comment]
你的服务器配置超过一页了吗？还是刚刚好占满一页

**Comment by Sam-Caesarmat** [comment]
> 你的服务器配置超过一页了吗？还是刚刚好占满一页

我的也是，服务器设置无法翻页且无法跟原来一样全选后批量删除服务器（节点大概有几百个😂 ）

**Comment by paradiseduo** [comment]
最新版本已经修复了这个问题
