### ISSUE TITLE
代理设置->高级设置->自动设置 关闭不了

### ISSUE THREAD

**Issue by zoltar9264** [paradiseduo/ShadowsocksX-NG-R8#14]
**System and Shadowsocksx-NG-R8 version:**

- macOS 10.15.3 (19D76)
- Shadowsocksx-NG-R8 1.6.1

代理设置->高级设置->自动设置按钮 每次取消选中后点确认后都没有生效，自动设置还是开启状态
![image](https://user-images.githubusercontent.com/16664055/79481836-95582480-8042-11ea-833e-fae738b9d1b0.png)
![image](https://user-images.githubusercontent.com/16664055/79481883-a5700400-8042-11ea-8522-e4f4bdc3701b.png)

**Comment by paradiseduo** [comment]
已经确认问题所在，下个版本会修复

**Comment by zoltar9264** [comment]
感谢大佬的工作！
