### ISSUE TITLE
一个问题和一个建议

### ISSUE THREAD

**Issue by ghost** [paradiseduo/ShadowsocksX-NG-R8#16]
能否说明下ACL自动模式和PAC的区别?ACL就是使用的软件目录下的.acl文件吗?另外一个建议就是不要增加自动选择低延迟节点连接,因为很多时候低延迟的节点并不是我想用的节点……如果要增加的话希望同时加上控制开关

**Comment by paradiseduo** [comment]
> 能否说明下ACL自动模式和PAC的区别?ACL就是使用的软件目录下的.acl文件吗?另外一个建议就是不要增加自动选择低延迟节点连接,因为很多时候低延迟的节点并不是我想用的节点……如果要增加的话希望同时加上控制开关

关于ACL和PAC的区别你可以看一下[这个](https://github.com/shadowsocks/ShadowsocksX-NG/issues/519#issuecomment-374503148)，另外我这个版本没有自动选择节点的功能。。
