### ISSUE TITLE
当登录时自动启动 和 打开时自动更新订阅 同时启用，开机或重启 会提示更新订阅失败

### ISSUE THREAD

**Issue by mingtochu** [paradiseduo/ShadowsocksX-NG-R8#17]
version: 1.6.2 (1)
macOS: 10.15.4 (19E287)
当登录时自动启动 和 打开时自动更新订阅 都被勾选了，
每一次开机或重启都会提示更新订阅失败，
<img width="223" alt="截屏2020-04-21 下午12 07 48" src="https://user-images.githubusercontent.com/11163821/79825560-e6ae3e00-83cb-11ea-8bd2-360d151bec3d.png">
<img width="339" alt="截屏2020-04-21 下午12 06 31" src="https://user-images.githubusercontent.com/11163821/79825562-e7df6b00-83cb-11ea-9d24-4097a6031505.png">

**Comment by paradiseduo** [comment]
你的这个订阅地址没被墙吧

**Comment by mingtochu** [comment]
订阅地址没有被墙，手动打开软件自动订阅是正常，
但是 登录时的自动启动 和 打开时自动更新订阅 同时启用，
每次开机时自动订阅都会失，但是手动更新则正常，
退出软件再重新打开时自动更新正常，
只是Mac开机或重启时 自动更新就会失败。

**Comment by paradiseduo** [comment]
> 订阅地址没有被墙，手动打开软件自动订阅是正常，
> 但是 登录时的自动启动 和 打开时自动更新订阅 同时启用，
> 每次开机时自动订阅都会失，但是手动更新则正常，
> 退出软件再重新打开时自动更新正常，
> 只是Mac开机或重启时 自动更新就会失败。

我这边两台电脑反复测试都是好用的（一台10.15.4，一台10.14.6），我再看看吧，估计是先后顺序的问题。

**Comment by paradiseduo** [comment]
你检查一下退出前选择的节点是否是可用的，如果选择了一个不可用的节点，会造成更新失败。

**Comment by mingtochu** [comment]
我也在2台Mac上都进行了测试，
开机自动启动订阅失败，
重启Mac自动订阅失败，
手动更新可是正常的哦！

**Comment by paradiseduo** [comment]
> 我也在2台Mac上都进行了测试，
> 开机自动启动订阅失败，
> 重启Mac自动订阅失败，
> 手动更新可是正常的哦！

你在不开启代理的情况下能更新订阅吗？

**Comment by mingtochu** [comment]
我又测试了不同的情况
更新订阅成功:  ☑️打开时自动更新订阅  ☑️打开时自动连接 （手动开启Shadowsocks）
更新订阅成功：Shadowsocks:Off   ☑️登录时自动启动   ☑️打开时自动更新订阅（自动开启Shadowsocks）

更新订阅失败：Shadowsocks:On  ☑️登录时自动启动   ☑️打开时自动更新订阅（自动开启Shadowsocks）
更新订阅失败：Shadowsocks:On  ☑️登录时自动启动   ☑️打开时自动更新订阅  ☑️打开时自动连接（自动开启Shadowsocks）

**Comment by paradiseduo** [comment]
> 我又测试了不同的情况
> 更新订阅成功: ☑️打开时自动更新订阅 ☑️打开时自动连接 （手动开启Shadowsocks）
> 更新订阅成功：Shadowsocks:Off ☑️登录时自动启动 ☑️打开时自动更新订阅（自动开启Shadowsocks）
> 
> 更新订阅失败：Shadowsocks:On ☑️登录时自动启动 ☑️打开时自动更新订阅（自动开启Shadowsocks）
> 更新订阅失败：Shadowsocks:On ☑️登录时自动启动 ☑️打开时自动更新订阅 ☑️打开时自动连接（自动开启Shadowsocks）

看你的描述，感觉是你选择的节点有问题。
在开启SSR的情况下订阅更新，更新请求是走代理的。
我这边测下来订阅失败可能会有三种原因：
1.开启代理的情况下订阅失败（说明选择的代理节点有问题）
2.关闭代理的情况下更新失败（说明订阅连接被墙）
3.任何情况下都更新失败（可能是电脑网络有问题[更新时电脑还没连上WiFi或者还没获取到IP地址]或者订阅地址有误）

**Comment by mingtochu** [comment]
我又进行了新的条件测试：
SSR使用PAC自动模式，自动更新订阅成功，手动更新订阅成功，
SSR使用白名单模式或ACL自动， 自动更新订阅失败（跟随系统启动），手动更新订阅成功。
