### ISSUE TITLE
你好，请问为什么点击手动更新订阅后不是显示更新成功，而是显示ICMP测试完成呢？

### ISSUE THREAD

**Issue by liuzhuang0305** [paradiseduo/ShadowsocksX-NG-R8#18]
![截屏2020-04-23 22 38 33](https://user-images.githubusercontent.com/56758778/80113459-e9b85280-85b4-11ea-89d5-989d05526c3d.png)

各版本如下：
macOS 10.15.4
Shadowsocksx-NG-R 1.6.2

**Comment by paradiseduo** [comment]
> ![截屏2020-04-23 22 38 33](https://user-images.githubusercontent.com/56758778/80113459-e9b85280-85b4-11ea-89d5-989d05526c3d.png)
> 
> 各版本如下：
> macOS 10.15.4
> Shadowsocksx-NG-R 1.6.2

点击通知中心，看看是不是有个更新成功。因为通知间隔时间太短，前一条通知被后一条覆盖了

**Comment by paradiseduo** [comment]
<img width="596" alt="WeChat0f0eeb07c476cfd75fb8333fbbfade86" src="https://user-images.githubusercontent.com/14846965/80174425-30459580-8625-11ea-8e1c-84985cee01e9.png">

**Comment by liuzhuang0305** [comment]
如图。我刚刚测试了一下，点击手动更新后还是显示的测试完成，通知中心不存在消息被覆盖的情况。





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"ParadiseDuo"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月24日(星期五) 中午12:13
收件人:&nbsp;"paradiseduo/ShadowsocksX-NG-R8"<ShadowsocksX-NG-R8@noreply.github.com&gt;;
抄送:&nbsp;"liuzhuang"<1301811082@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [paradiseduo/ShadowsocksX-NG-R8] 你好，请问为什么点击手动更新订阅后不是显示更新成功，而是显示ICMP测试完成呢？ (#18)





  

 
各版本如下：
 macOS 10.15.4
 Shadowsocksx-NG-R 1.6.2
  
点击通知中心，看看是不是有个更新成功。因为前一条通知被后一条覆盖了

**Comment by paradiseduo** [comment]
> 如图。我刚刚测试了一下，点击手动更新后还是显示的测试完成，通知中心不存在消息被覆盖的情况。
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"ParadiseDuo"<notifications@github.com&gt;; 发送时间:&nbsp;2020年4月24日(星期五) 中午12:13 收件人:&nbsp;"paradiseduo/ShadowsocksX-NG-R8"<ShadowsocksX-NG-R8@noreply.github.com&gt;; 抄送:&nbsp;"liuzhuang"<1301811082@qq.com&gt;;"Author"<author@noreply.github.com&gt;; 主题:&nbsp;Re: [paradiseduo/ShadowsocksX-NG-R8] 你好，请问为什么点击手动更新订阅后不是显示更新成功，而是显示ICMP测试完成呢？ (#18) 各版本如下： macOS 10.15.4 Shadowsocksx-NG-R 1.6.2 点击通知中心，看看是不是有个更新成功。因为前一条通知被后一条覆盖了 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

没看到图啊

**Comment by liuzhuang0305** [comment]
你好，我重新发了一遍，&nbsp; 图见附件。







---原始邮件---
发件人: "ParadiseDuo"<notifications@github.com&gt;
发送时间: 2020年4月24日(周五) 中午12:13
收件人: "paradiseduo/ShadowsocksX-NG-R8"<ShadowsocksX-NG-R8@noreply.github.com&gt;;
抄送: "liuzhuang"<1301811082@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [paradiseduo/ShadowsocksX-NG-R8] 你好，请问为什么点击手动更新订阅后不是显示更新成功，而是显示ICMP测试完成呢？ (#18)




  

 
各版本如下：
 macOS 10.15.4
 Shadowsocksx-NG-R 1.6.2
  
点击通知中心，看看是不是有个更新成功。因为前一条通知被后一条覆盖了

**Comment by paradiseduo** [comment]
> 你好，我重新发了一遍，&nbsp; 图见附件。
> […](#)
> ---原始邮件--- 发件人: "ParadiseDuo"<notifications@github.com&gt; 发送时间: 2020年4月24日(周五) 中午12:13 收件人: "paradiseduo/ShadowsocksX-NG-R8"<ShadowsocksX-NG-R8@noreply.github.com&gt;; 抄送: "liuzhuang"<1301811082@qq.com&gt;;"Author"<author@noreply.github.com&gt;; 主题: Re: [paradiseduo/ShadowsocksX-NG-R8] 你好，请问为什么点击手动更新订阅后不是显示更新成功，而是显示ICMP测试完成呢？ (#18) 各版本如下： macOS 10.15.4 Shadowsocksx-NG-R 1.6.2 点击通知中心，看看是不是有个更新成功。因为前一条通知被后一条覆盖了 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

你需要在github上回复，邮件回复看不到图片的
