### ISSUE TITLE
关于菜单图标

### ISSUE THREAD

**Issue by minoism** [paradiseduo/ShadowsocksX-NG-R8#21]
- macOS 10.15.4
- 三天前更新的版本

如图，白天情况下它非常的丑陋
![image](https://user-images.githubusercontent.com/58068445/80436228-4313df00-8931-11ea-9109-c6d6bfe475b0.png)

![image](https://user-images.githubusercontent.com/58068445/80436219-3e4f2b00-8931-11ea-8b25-b3599a4b383c.png)

**Comment by paradiseduo** [comment]
我这边切换明暗模式是正常的，你试一下手动在 系统偏好设置->通用->外观 里面切换明暗模式，图标会跟随系统变化吗？

**Comment by minoism** [comment]
> 我这边切换明暗模式是正常的，你试一下手动在 系统偏好设置->通用->外观 里面切换明暗模式，图标会跟随系统变化吗？

可以了！不过貌似不是纯黑色，有点灰
![image](https://user-images.githubusercontent.com/58068445/80566149-e0037480-8a24-11ea-9c55-7ab12a15f865.png)

**Comment by paradiseduo** [comment]
> > 我这边切换明暗模式是正常的，你试一下手动在 系统偏好设置->通用->外观 里面切换明暗模式，图标会跟随系统变化吗？
> 
> 可以了！不过貌似不是纯黑色，有点灰
> ![image](https://user-images.githubusercontent.com/58068445/80566149-e0037480-8a24-11ea-9c55-7ab12a15f865.png)

对的，原版设计就是这样，因为我没有制作icon的能力，所以一直在考虑要不要做成Windows那样，根据颜色来区分各种模式，这样就不需要设计和区分明暗模式的图标了

**Comment by minoism** [comment]
> > > 我这边切换明暗模式是正常的，你试一下手动在 系统偏好设置->通用->外观 里面切换明暗模式，图标会跟随系统变化吗？
> > 
> > 
> > 可以了！不过貌似不是纯黑色，有点灰
> > ![image](https://user-images.githubusercontent.com/58068445/80566149-e0037480-8a24-11ea-9c55-7ab12a15f865.png)
> 
> 对的，原版设计就是这样，因为我没有制作icon的能力，所以一直在考虑要不要做成Windows那样，根据颜色来区分各种模式，这样就不需要设计和区分明暗模式的图标了

我可以提个纯黑色图标的pr吗

**Comment by paradiseduo** [comment]
可以啊，一共有6个图标需要替换。分辨率为18x18 36x36 54x54

**Comment by minoism** [comment]
> 可以啊，一共有6个图标需要替换。分辨率为18x18 36x36 54x54

已提交👌

**Comment by minoism** [comment]
另外的话图标与网速之间的边距过大了感觉怪怪的
![image](https://user-images.githubusercontent.com/58068445/80570707-dcc0b680-8a2d-11ea-88d0-440ad732b2e4.png)

**Comment by paradiseduo** [comment]
> 另外的话图标与网速之间的边距过大了感觉怪怪的
> ![image](https://user-images.githubusercontent.com/58068445/80570707-dcc0b680-8a2d-11ea-88d0-440ad732b2e4.png)

这个没有办法，目前不能做间距跟随字体宽度进行改变，包括成熟的系统信息显示APP  iStat Menus，因为当初mac系统设计状态栏的时候就没考虑让他自动变化。

**Comment by minoism** [comment]
> 这个没有办法，目前做不到间距跟随字体宽度进行改变，包括成熟的系统信息显示APP iStat Menus

如果只是换个方向呢，上下箭头图标在左，文字在右

它可能是这样子:
![image](https://user-images.githubusercontent.com/58068445/80572135-4fcb2c80-8a30-11ea-81cf-ba5466912c03.png)

**Comment by paradiseduo** [comment]
> > 这个没有办法，目前做不到间距跟随字体宽度进行改变，包括成熟的系统信息显示APP iStat Menus
> 
> 如果只是换个方向呢，上下箭头图标在左，文字在右
> 
> 它可能是这样子:
> ![image](https://user-images.githubusercontent.com/58068445/80572135-4fcb2c80-8a30-11ea-81cf-ba5466912c03.png)

这样做的话，和其他APP之前的空隙就变大了。
另外我尝试了一下每次更新网速的时候更新图标宽度，效果不好，状态栏一直在跳动（因为一个item的width变了，其他应用的item位置要跟着变）

**Comment by minoism** [comment]
> 这样做的话，和其他APP之前的空隙就变大了。

不懂 mac 的状态栏...不可以指定宽度吗，如果可以的话有一个最大宽度这样应该也不会大很多

**Comment by paradiseduo** [comment]
如果按照左对齐的方案，最终效果是这个样子：
![image](https://user-images.githubusercontent.com/14846965/80578752-91150980-8a3b-11ea-927f-afc6f25a7b46.png)
如果再窄的话，当显示大于10.00MB/s网速的时候后面的/s会被截掉

**Comment by paradiseduo** [comment]
如果是每次都改变宽度，大概是这个样子：
<img width="586" alt="WeChat3bde06d5fd04ac48a90ecc310a9997d2" src="https://user-images.githubusercontent.com/14846965/80579032-f8cb5480-8a3b-11ea-8e4f-3c13bdd09061.png">

**Comment by minoism** [comment]
> 如果按照左对齐的方案，最终效果是这个样子：
> ![image](https://user-images.githubusercontent.com/14846965/80578752-91150980-8a3b-11ea-927f-afc6f25a7b46.png)
> 如果在窄的话，当显示大于10.00MB/s网速的时候后面的/s会被截掉

虽然还是怪怪的，但是感觉比原来好很多了...
如果是这样加个分割线呢:
![80578752-91150980-8a3b-11ea-927f-afc6f25a7b46副本](https://user-images.githubusercontent.com/58068445/80579512-be15ec00-8a3c-11ea-949e-650d2924a7f1.png)

**Comment by minoism** [comment]
> 如果是每次都改变宽度，大概是这个样子：
> <img alt="WeChat3bde06d5fd04ac48a90ecc310a9997d2" width="586" src="https://user-images.githubusercontent.com/14846965/80579032-f8cb5480-8a3b-11ea-8e4f-3c13bdd09061.png">
> 状态栏没办法截取gif，只能截个png了

这个效果很棒！但是如果网速刷新导致图标位置一直跳动感觉也不好

**Comment by paradiseduo** [comment]
> > 如果是每次都改变宽度，大概是这个样子：
> > <img alt="WeChat3bde06d5fd04ac48a90ecc310a9997d2" width="586" src="https://user-images.githubusercontent.com/14846965/80579032-f8cb5480-8a3b-11ea-8e4f-3c13bdd09061.png">
> > 状态栏没办法截取gif，只能截个png了
> 
> 这个效果很棒！但是如果网速刷新导致图标位置一直跳动感觉也不好

找了个录制gif的工具，上传个gif看看：
![1](https://user-images.githubusercontent.com/14846965/80580025-7b084880-8a3d-11ea-962a-c1294c8130b4.gif)

**Comment by minoism** [comment]
> 找了个录制gif的工具，上传个gif看看：
> ![1](https://user-images.githubusercontent.com/14846965/80580025-7b084880-8a3d-11ea-962a-c1294c8130b4.gif)

看起来蛮不错的。提个建议：加入设置，可以自己选择对齐方式

**Comment by paradiseduo** [comment]
下个版本会加。
另外会考虑优化一下设置，加个设置页面，现在列表里的勾太多了，统一一下入口。

**Comment by minoism** [comment]
> 我这边切换明暗模式是正常的，你试一下手动在 系统偏好设置->通用->外观 里面切换明暗模式，图标会跟随系统变化吗？

今天开电脑发现图标又变成白色了

目前情况：
浅色模式到点了自动切换到深色模式时，菜单图标会自动从黑色变为白色
到了白天时，自动切换深色 >> 浅色模式，菜单图标没有任何改变也就导致了图二
![image](https://user-images.githubusercontent.com/58068445/80670633-06371c00-8ada-11ea-8342-3b9184801aee.png)

![](https://user-images.githubusercontent.com/58068445/80436228-4313df00-8931-11ea-9109-c6d6bfe475b0.png)

**Comment by paradiseduo** [comment]
这个问题我再研究一下，我一直都是用一种模式的，所以没发现这个问题。

**Comment by minoism** [comment]
测试了一下这个的菜单图标没有问题，不知道是否对修复有帮助：https://github.com/shadowsocks/ShadowsocksX-NG

**Comment by Sam-Caesarmat** [comment]
> > > 我这边切换明暗模式是正常的，你试一下手动在 系统偏好设置->通用->外观 里面切换明暗模式，图标会跟随系统变化吗？
> > 
> > 
> > 可以了！不过貌似不是纯黑色，有点灰
> > ![image](https://user-images.githubusercontent.com/58068445/80566149-e0037480-8a24-11ea-9c55-7ab12a15f865.png)
> 
> 对的，原版设计就是这样，因为我没有制作icon的能力，所以一直在考虑要不要做成Windows那样，根据颜色来区分各种模式，这样就不需要设计和区分明暗模式的图标了

还是别了，一到夜间模式，状态栏其他都是白的，就这小飞机花花绿绿的有点突兀🧐🧐

**Comment by Sam-Caesarmat** [comment]
> > > 如果是每次都改变宽度，大概是这个样子：
> > > <img alt="WeChat3bde06d5fd04ac48a90ecc310a9997d2" width="586" src="https://user-images.githubusercontent.com/14846965/80579032-f8cb5480-8a3b-11ea-8e4f-3c13bdd09061.png">
> > > 状态栏没办法截取gif，只能截个png了
> > 
> > 
> > 这个效果很棒！但是如果网速刷新导致图标位置一直跳动感觉也不好
> 
> 找了个录制gif的工具，上传个gif看看：
> ![1](https://user-images.githubusercontent.com/14846965/80580025-7b084880-8a3d-11ea-962a-c1294c8130b4.gif)

网速动还好，如果图标跟着一块动会不会有点吸引注意力😂😂

**Comment by paradiseduo** [comment]
> > > > 如果是每次都改变宽度，大概是这个样子：
> > > > <img alt="WeChat3bde06d5fd04ac48a90ecc310a9997d2" width="586" src="https://user-images.githubusercontent.com/14846965/80579032-f8cb5480-8a3b-11ea-8e4f-3c13bdd09061.png">
> > > > 状态栏没办法截取gif，只能截个png了
> > > 
> > > 
> > > 这个效果很棒！但是如果网速刷新导致图标位置一直跳动感觉也不好
> > 
> > 
> > 找了个录制gif的工具，上传个gif看看：
> > ![1](https://user-images.githubusercontent.com/14846965/80580025-7b084880-8a3d-11ea-962a-c1294c8130b4.gif)
> 
> 网速动还好，如果图标跟着一块动会不会有点吸引注意力😂😂

我把显示网速模块独立出来了，下个版本看看反馈
