### ISSUE TITLE
绕过中国大陆

### ISSUE THREAD

**Issue by minoism** [paradiseduo/ShadowsocksX-NG-R8#22]
mac ssr客户端有像windows那样可以设置全局代理但是绕过中国大陆的选项吗，设置为pac模式时，有些外网访问不到，设置全局模式的话没有问题，但是国内的也会走代理

**Comment by paradiseduo** [comment]
白名单模式

**Comment by paradiseduo** [comment]
也可以安装SwitchyOmega插件来解决，SwitchyOmega支持Firefox和Chromium（Chrome、新版Edge）内核的浏览器

**Comment by minoism** [comment]
> 白名单模式

成功，目前好像没有问题了！
