### ISSUE TITLE
小小建议

### ISSUE THREAD

**Issue by tabit2** [paradiseduo/ShadowsocksX-NG-R8#24]
1.延迟测试方式是否方便增加一个Google ping？因为中转过的节点用TCP Ping并不能测出是否正常
2.代理设置->更新ALC名单，这应该是“ACL名单”吧？
3.PAL自动和ACL自动能否实现共用一套规则？（或者可以考虑加入一个“ACL用户自定义规则”的功能）

**Comment by paradiseduo** [comment]
1.Google ping暂时无法实现，clash可以做是因为底层的clash库本身支持这种测试方式，SSR只能是设置系统代理，然后用curl命令去测，如果你有几百个节点就要设置几百次代理，这样会使电脑出问题而且测试时间很长。
其实现在的tcping也有问题，如果同时测几百个节点，那么测出来的延迟会巨高无比。分组测的话时间就会太长（现在是每秒测一次，测5秒取平均值）。

2.更新ALC名单这里是手误，下个版本改一下

3.PAC跟ACL实现的原理不太一样，因此要共用难度很大（其实我不会，是我太菜了）。。
如果要改ACL文件的话可以在这里改：
```bash
➜ cd ~/.ShadowsocksX-NG
➜ ls
backchn.acl         gfwlist.acl         gfwlist.txt         user-rule.txt
chn.acl             gfwlist.js          user-privoxy.config
➜ open .
```
