### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by Sam-Caesarmat** [paradiseduo/ShadowsocksX-NG-R8#25]
1、被隔开了，需要手动再交换顺序（有时退出再打开仍会相隔较远）
![image](https://user-images.githubusercontent.com/42537544/80801850-3537b580-8be0-11ea-9916-8d7a9ed9038e.png)

2、在服务器设置中，将节点全部删除后在菜单中仍会显示（下图1），且小飞机仍为打开的状态（下图2）在此期间无法将其改为关闭状态。
![image](https://user-images.githubusercontent.com/42537544/80802092-e3dbf600-8be0-11ea-9c30-46131f2edbde.png)
![image](https://user-images.githubusercontent.com/42537544/80802226-5d73e400-8be1-11ea-9e97-74a78ed192b8.png)

**Comment by Sam-Caesarmat** [comment]
小飞机和网速分开以后，小飞机的图标会随网速变化左右动，导致小飞机左边的图标一块跟着动，有点吸引注意。😂😂

**Comment by paradiseduo** [comment]
被隔开是有意而为的，目的是让大家把显示网速作为一个附加功能。

至于一直跳动，这个会做优化。目前考虑在设置里增加一个选项让宽度固定。

删除所有节点的bug我研究一下。

**Comment by Sam-Caesarmat** [comment]
> 被隔开是有意而为的，目的是让大家把显示网速作为一个附加功能。
> 
> 至于一直跳动，这个会做优化。目前考虑在设置里增加一个选项让宽度固定。
> 
> 删除所有节点的bug我研究一下。

嗯嗯，麻烦大佬了，以前想要召唤菜单的时候点击图标和网速都可以，现在必须要点图标，鼠标点击区域小了有点不太适应😂

对了大佬，要不要考虑下把删除订阅链接时将其对应的节点一起删除的功能。

**Comment by paradiseduo** [comment]
release 1.6.5
