### ISSUE TITLE
ss-local 貌似没启动

### ISSUE THREAD

**Issue by chenqinghe** [paradiseduo/ShadowsocksX-NG-R8#26]
启动shadowsocks之后，使用ps aux|grep ss-local，发现没有启动，并且端口也没有在监听。手动启动library/application support/Shadowsocks-NG-R8下的ss-local之后，可以正常使用了。但是这样修改服务器之后，还要重新启动ss-local，为啥自动shadowsocks的时候没有启动ss-local?有啥办法解决这个问题吗？

**Comment by paradiseduo** [comment]
我没看明白，你用的是哪个版本，系统版本是多少，你说的启动是打开APP还是点击了菜单中的启动？你说的自动shadowsocks是指什么？是PAC自动还是ACL自动还是开机自动启动APP还是打开APP后自动连接？
最好能像#21 #25 那样图文并茂的提问题，那样能快速的定位问题所在。

**Comment by zhangdong1016** [comment]
如果你安装了类似于CleanMyMac X等软件，请在优化-启动代理选项中查看是否有类似com.Shadowsocks选项被禁用

**Comment by Mr-AlbertZhang** [comment]
> 启动shadowsocks之后，使用ps aux|grep ss-local，发现没有启动，并且端口也没有在监听。手动启动library/application support/Shadowsocks-NG-R8下的ss-local之后，可以正常使用了。但是这样修改服务器之后，还要重新启动ss-local，为啥自动shadowsocks的时候没有启动ss-local?有啥办法解决这个问题吗？

如果你安装了类似于CleanMyMac X等软件，请在优化-启动代理选项中查看是否有类似com.Shadowsocks选项被禁用

**Comment by chenqinghe** [comment]
软件版本是最新版1.6.5，系统版本macOS Mojave 10.14.6。启动方式是打开app。代理是全局模式。1080端口也并没有被占用。但是ss-local程序就是没有起来。

**Comment by chenqinghe** [comment]
@Mr-AlbertZhang emm.....没有安装这类软件

**Comment by paradiseduo** [comment]
检查一下启动项里是否有这两个plist文件：
```bash
➜  ~ cd ~/Library/LaunchAgents/
➜  LaunchAgents ls | grep shadow
com.qiuyuzhou.shadowsocksX-NG.http.plist
com.qiuyuzhou.shadowsocksX-NG.local.plist
```
如果有的话，检查一下文件内容(your name 是你Mac的用户名)：
```bash
➜  LaunchAgents cat com.qiuyuzhou.shadowsocksX-NG.local.plist
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>EnvironmentVariables</key>
	<dict>
		<key>DYLD_LIBRARY_PATH</key>
		<string>/Users/your name/Library/Application Support/ShadowsocksX-NG-R8/</string>
	</dict>
	<key>KeepAlive</key>
	<true/>
	<key>Label</key>
	<string>com.qiuyuzhou.shadowsocksX-NG.local</string>
	<key>ProgramArguments</key>
	<array>
		<string>/Users/your name/Library/Application Support/ShadowsocksX-NG-R8/ss-local</string>
		<string>-c</string>
		<string>ss-local-config.json</string>
		<string>--fast-open</string>
	</array>
	<key>StandardErrorPath</key>
	<string>/Users/your name/Library/Logs/ss-local.log</string>
	<key>StandardOutPath</key>
	<string>/Users/your name/Library/Logs/ss-local.log</string>
	<key>WorkingDirectory</key>
	<string>/Users/your name/Library/Application Support/ShadowsocksX-NG-R8/</string>
</dict>
</plist>

➜  LaunchAgents cat com.qiuyuzhou.shadowsocksX-NG.http.plist
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>EnvironmentVariables</key>
	<dict>
		<key>DYLD_LIBRARY_PATH</key>
		<string>/Users/your name/Library/Application Support/ShadowsocksX-NG-R8/</string>
	</dict>
	<key>KeepAlive</key>
	<true/>
	<key>Label</key>
	<string>com.qiuyuzhou.shadowsocksX-NG.http</string>
	<key>ProgramArguments</key>
	<array>
		<string>/Users/your name/Library/Application Support/ShadowsocksX-NG-R8/privoxy</string>
		<string>--no-daemon</string>
		<string>privoxy.config</string>
	</array>
	<key>StandardErrorPath</key>
	<string>/Users/your name/Library/Logs/privoxy.log</string>
	<key>StandardOutPath</key>
	<string>/Users/your name/Library/Logs/privoxy.log</string>
	<key>WorkingDirectory</key>
	<string>/Users/your name/Library/Application Support/ShadowsocksX-NG-R8/</string>
</dict>
</plist>
```

**Comment by chenqinghe** [comment]
这两个文件是有的：

```
➜  LaunchAgents ll
total 48
-rw-r--r--@ 1 chenqinghe  staff   812B  3 12 19:30 com.google.keystone.agent.plist
-rw-r--r--@ 1 chenqinghe  staff   918B  3 12 19:30 com.google.keystone.xpcservice.plist
-rw-r--r--  1 chenqinghe  staff   944B  5  2 17:15 com.qiuyuzhou.shadowsocksX-NG.http.plist
-rw-r--r--  1 chenqinghe  staff   919B  8 29  2018 com.qiuyuzhou.shadowsocksX-NG.kcptun.plist
-rw-r--r--  1 chenqinghe  staff   998B  5  2 17:15 com.qiuyuzhou.shadowsocksX-NG.local.plist
-rw-r--r--  1 chenqinghe  staff   481B  9  9  2019 com.sogou.SogouTaskManager.plist
```

文件内容：

```
➜  LaunchAgents cat com.qiuyuzhou.shadowsocksX-NG.http.plist
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>EnvironmentVariables</key>
	<dict>
		<key>DYLD_LIBRARY_PATH</key>
		<string>/Users/chenqinghe/Library/Application Support/ShadowsocksX-NG-R8/</string>
	</dict>
	<key>KeepAlive</key>
	<true/>
	<key>Label</key>
	<string>com.qiuyuzhou.shadowsocksX-NG.http</string>
	<key>ProgramArguments</key>
	<array>
		<string>/Users/chenqinghe/Library/Application Support/ShadowsocksX-NG-R8/privoxy</string>
		<string>--no-daemon</string>
		<string>privoxy.config</string>
	</array>
	<key>StandardErrorPath</key>
	<string>/Users/chenqinghe/Library/Logs/privoxy.log</string>
	<key>StandardOutPath</key>
	<string>/Users/chenqinghe/Library/Logs/privoxy.log</string>
	<key>WorkingDirectory</key>
	<string>/Users/chenqinghe/Library/Application Support/ShadowsocksX-NG-R8/</string>
</dict>
</plist>
```

```
➜  LaunchAgents cat com.qiuyuzhou.shadowsocksX-NG.local.plist
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>EnvironmentVariables</key>
	<dict>
		<key>DYLD_LIBRARY_PATH</key>
		<string>/Users/chenqinghe/Library/Application Support/ShadowsocksX-NG-R8/</string>
	</dict>
	<key>KeepAlive</key>
	<true/>
	<key>Label</key>
	<string>com.qiuyuzhou.shadowsocksX-NG.local</string>
	<key>ProgramArguments</key>
	<array>
		<string>/Users/chenqinghe/Library/Application Support/ShadowsocksX-NG-R8/ss-local</string>
		<string>-c</string>
		<string>ss-local-config.json</string>
		<string>--fast-open</string>
		<string>-v</string>
	</array>
	<key>StandardErrorPath</key>
	<string>/Users/chenqinghe/Library/Logs/ss-local.log</string>
	<key>StandardOutPath</key>
	<string>/Users/chenqinghe/Library/Logs/ss-local.log</string>
	<key>WorkingDirectory</key>
	<string>/Users/chenqinghe/Library/Application Support/ShadowsocksX-NG-R8/</string>
</dict>
</plist>
```

**Comment by paradiseduo** [comment]
你之前装过别的版本吗？
看一下Log：
```bash
cat ~/Library/Logs/ss-local.log
```

**Comment by chenqinghe** [comment]
抱歉，重启了一下，现在可以了。

之前装过别的版本，但是具体什么版本不记得了。前段时间突然不能科学上网了，然后重新下载了最新版本，打开app后发现还是不行，本地1080端口都没在监听，然后发现ss-local没有启动，重装几次都没有用。刚才重启了下电脑，其他啥都没干发现又好了……

实在抱歉，耽误了你不少时间……

**Comment by Mr-AlbertZhang** [comment]
> 检查一下启动项里是否有这两个plist文件：
> 
> ```shell
> ➜  ~ cd ~/Library/LaunchAgents/
> ➜  LaunchAgents ls | grep shadow
> com.qiuyuzhou.shadowsocksX-NG.http.plist
> com.qiuyuzhou.shadowsocksX-NG.local.plist
> ```
> 
> 如果有的话，检查一下文件内容(your name 是你Mac的用户名)：
> 
> ```shell
> ➜  LaunchAgents cat com.qiuyuzhou.shadowsocksX-NG.local.plist
> <?xml version="1.0" encoding="UTF-8"?>
> <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
> <plist version="1.0">
> <dict>
> 	<key>EnvironmentVariables</key>
> 	<dict>
> 		<key>DYLD_LIBRARY_PATH</key>
> 		<string>/Users/your name/Library/Application Support/ShadowsocksX-NG-R8/</string>
> 	</dict>
> 	<key>KeepAlive</key>
> 	<true/>
> 	<key>Label</key>
> 	<string>com.qiuyuzhou.shadowsocksX-NG.local</string>
> 	<key>ProgramArguments</key>
> 	<array>
> 		<string>/Users/your name/Library/Application Support/ShadowsocksX-NG-R8/ss-local</string>
> 		<string>-c</string>
> 		<string>ss-local-config.json</string>
> 		<string>--fast-open</string>
> 	</array>
> 	<key>StandardErrorPath</key>
> 	<string>/Users/your name/Library/Logs/ss-local.log</string>
> 	<key>StandardOutPath</key>
> 	<string>/Users/your name/Library/Logs/ss-local.log</string>
> 	<key>WorkingDirectory</key>
> 	<string>/Users/your name/Library/Application Support/ShadowsocksX-NG-R8/</string>
> </dict>
> </plist>
> 
> ➜  LaunchAgents cat com.qiuyuzhou.shadowsocksX-NG.http.plist
> <?xml version="1.0" encoding="UTF-8"?>
> <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
> <plist version="1.0">
> <dict>
> 	<key>EnvironmentVariables</key>
> 	<dict>
> 		<key>DYLD_LIBRARY_PATH</key>
> 		<string>/Users/your name/Library/Application Support/ShadowsocksX-NG-R8/</string>
> 	</dict>
> 	<key>KeepAlive</key>
> 	<true/>
> 	<key>Label</key>
> 	<string>com.qiuyuzhou.shadowsocksX-NG.http</string>
> 	<key>ProgramArguments</key>
> 	<array>
> 		<string>/Users/your name/Library/Application Support/ShadowsocksX-NG-R8/privoxy</string>
> 		<string>--no-daemon</string>
> 		<string>privoxy.config</string>
> 	</array>
> 	<key>StandardErrorPath</key>
> 	<string>/Users/your name/Library/Logs/privoxy.log</string>
> 	<key>StandardOutPath</key>
> 	<string>/Users/your name/Library/Logs/privoxy.log</string>
> 	<key>WorkingDirectory</key>
> 	<string>/Users/your name/Library/Application Support/ShadowsocksX-NG-R8/</string>
> </dict>
> </plist>
> ```

我的貌似就经常出现问题，我安装了CleanMyMac X 在里面有个启动代理选择项 有时候不监听的时候我需要把这local和http这两个选项勾选取消再勾选启用就可以了，这个有没有解决办法？

**Comment by paradiseduo** [comment]
> > 检查一下启动项里是否有这两个plist文件：
> > ```shell
> > ➜  ~ cd ~/Library/LaunchAgents/
> > ➜  LaunchAgents ls | grep shadow
> > com.qiuyuzhou.shadowsocksX-NG.http.plist
> > com.qiuyuzhou.shadowsocksX-NG.local.plist
> > ```
> > 
> > 
> > 如果有的话，检查一下文件内容(your name 是你Mac的用户名)：
> > ```shell
> > ➜  LaunchAgents cat com.qiuyuzhou.shadowsocksX-NG.local.plist
> > <?xml version="1.0" encoding="UTF-8"?>
> > <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
> > <plist version="1.0">
> > <dict>
> > 	<key>EnvironmentVariables</key>
> > 	<dict>
> > 		<key>DYLD_LIBRARY_PATH</key>
> > 		<string>/Users/your name/Library/Application Support/ShadowsocksX-NG-R8/</string>
> > 	</dict>
> > 	<key>KeepAlive</key>
> > 	<true/>
> > 	<key>Label</key>
> > 	<string>com.qiuyuzhou.shadowsocksX-NG.local</string>
> > 	<key>ProgramArguments</key>
> > 	<array>
> > 		<string>/Users/your name/Library/Application Support/ShadowsocksX-NG-R8/ss-local</string>
> > 		<string>-c</string>
> > 		<string>ss-local-config.json</string>
> > 		<string>--fast-open</string>
> > 	</array>
> > 	<key>StandardErrorPath</key>
> > 	<string>/Users/your name/Library/Logs/ss-local.log</string>
> > 	<key>StandardOutPath</key>
> > 	<string>/Users/your name/Library/Logs/ss-local.log</string>
> > 	<key>WorkingDirectory</key>
> > 	<string>/Users/your name/Library/Application Support/ShadowsocksX-NG-R8/</string>
> > </dict>
> > </plist>
> > 
> > ➜  LaunchAgents cat com.qiuyuzhou.shadowsocksX-NG.http.plist
> > <?xml version="1.0" encoding="UTF-8"?>
> > <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
> > <plist version="1.0">
> > <dict>
> > 	<key>EnvironmentVariables</key>
> > 	<dict>
> > 		<key>DYLD_LIBRARY_PATH</key>
> > 		<string>/Users/your name/Library/Application Support/ShadowsocksX-NG-R8/</string>
> > 	</dict>
> > 	<key>KeepAlive</key>
> > 	<true/>
> > 	<key>Label</key>
> > 	<string>com.qiuyuzhou.shadowsocksX-NG.http</string>
> > 	<key>ProgramArguments</key>
> > 	<array>
> > 		<string>/Users/your name/Library/Application Support/ShadowsocksX-NG-R8/privoxy</string>
> > 		<string>--no-daemon</string>
> > 		<string>privoxy.config</string>
> > 	</array>
> > 	<key>StandardErrorPath</key>
> > 	<string>/Users/your name/Library/Logs/privoxy.log</string>
> > 	<key>StandardOutPath</key>
> > 	<string>/Users/your name/Library/Logs/privoxy.log</string>
> > 	<key>WorkingDirectory</key>
> > 	<string>/Users/your name/Library/Application Support/ShadowsocksX-NG-R8/</string>
> > </dict>
> > </plist>
> > ```
> 
> 我的貌似就经常出现问题，我安装了CleanMyMac X 在里面有个启动代理选择项 有时候不监听的时候我需要把这local和http这两个选项勾选取消再勾选启用就可以了，这个有没有解决办法？

我目前没有遇到过这种情况，暂时没有好的解决方案。
另外你这边是不是不经常关电脑啊？

**Comment by Mr-AlbertZhang** [comment]
> > 
> > 
> > 我的貌似就经常出现问题，我安装了CleanMyMac X 在里面有个启动代理选择项 有时候不监听的时候我需要把这local和http这两个选项勾选取消再勾选启用就可以了，这个有没有解决办法？
> 
> 我目前没有遇到过这种情况，暂时没有好的解决方案。
> 另外你这边是不是不经常关电脑啊？

是的 我没有关电脑的习惯😓，应该说除了必要的升级系统重启，我从来没有关过，都是合上本就走，打开本就用😢，这是不是很不好😥的习惯啊😱😱😱

**Comment by paradiseduo** [comment]
> > > 我的貌似就经常出现问题，我安装了CleanMyMac X 在里面有个启动代理选择项 有时候不监听的时候我需要把这local和http这两个选项勾选取消再勾选启用就可以了，这个有没有解决办法？
> > 
> > 
> > 我目前没有遇到过这种情况，暂时没有好的解决方案。
> > 另外你这边是不是不经常关电脑啊？
> 
> 是的 我没有关电脑的习惯😓，应该说除了必要的升级系统重启，我从来没有关过，都是合上本就走，打开本就用😢，这是不是很不好😥的习惯啊😱😱😱

那这可能就是问题所在了，我的使用习惯是每天下班关机，上班开机，所以从来没有遇到启动项加载失败的问题。。
包括最近有人提到测速功能不好使，也是因为长时间不关机导致的。
这些看上去更像是macOS的问题。
毕竟：

![image](https://user-images.githubusercontent.com/14846965/81526085-42476800-9389-11ea-91d6-d33d471fee9e.png)
![image](https://user-images.githubusercontent.com/14846965/81526112-55f2ce80-9389-11ea-8561-e5db9da780ca.png)

**Comment by Mr-AlbertZhang** [comment]
> > > > 我的貌似就经常出现问题，我安装了CleanMyMac X 在里面有个启动代理选择项 有时候不监听的时候我需要把这local和http这两个选项勾选取消再勾选启用就可以了，这个有没有解决办法？
> > > 
> > > 
> > > 我目前没有遇到过这种情况，暂时没有好的解决方案。
> > > 另外你这边是不是不经常关电脑啊？
> > 
> > 
> > 是的 我没有关电脑的习惯😓，应该说除了必要的升级系统重启，我从来没有关过，都是合上本就走，打开本就用😢，这是不是很不好😥的习惯啊😱😱😱
> 
> 那这可能就是问题所在了，我的使用习惯是每天下班关机，上班开机，所以从来没有遇到启动项加载失败的问题。。
> 包括最近有人提到测速功能不好使，也是因为长时间不关机导致的。
> 这些看上去更像是macOS的问题。
> 毕竟：
> 
> ![image](https://user-images.githubusercontent.com/14846965/81526085-42476800-9389-11ea-91d6-d33d471fee9e.png)
> ![image](https://user-images.githubusercontent.com/14846965/81526112-55f2ce80-9389-11ea-8561-e5db9da780ca.png)

人才 人才。。。。get到新技能 谢谢。。。。。😇😇
