### ISSUE TITLE
手动订阅失败（1.65）

### ISSUE THREAD

**Issue by Mr-AlbertZhang** [paradiseduo/ShadowsocksX-NG-R8#27]
1.6.4覆盖更新新版本（1.6.5），手动订阅会概率性返回请求失败（超过50%），ICMP测速成功。
关闭程序后重新打开，概率性返回订阅成功（已经设开启自动订阅）ICMP测速成功。
查阅服务器端可以看到订阅记录（失败也可以查询到订阅记录）
退回1.6.4 手动或者自动均未发现以上问题。
OS：10.15.4 (19E287)

**Comment by paradiseduo** [comment]
我研究研究，你的订阅地址没有被墙吧？

**Comment by Mr-AlbertZhang** [comment]
> 我研究研究，你的订阅地址没有被墙吧？

  订阅地址不科学上网直接复制到浏览器可以完全下载下来，没有发现被墙的情况

**Comment by paradiseduo** [comment]
我这边测试了一天1.6.5版本，没有出现请求失败的情况，除非是订阅地址被墙，并且当前选择了一个国内的节点（无法翻墙的节点），这样会导致更新失败。

目前请求超时设置的是5s，如果超过5s没有返回结果，也会显示订阅失败。

**Comment by Mr-AlbertZhang** [comment]
1.6.4的超时设置也是5S吗？墙的可能性不大，因为即使软件显示订阅失败，在服务器端也可以查看到该时间的订阅记录，实际上是订阅成功的，我猜想由于网络质量及节点导致5S以后传输到端，所以会显示失败。也可能是我已经订阅到节点（已经自由），再手动更新订阅，在节点网络不好的情况下这个数据传输必然返回超过5S。建议评估国内网络不好的情况下在后版本延长超时时间？感谢答主~美好的软件

**Comment by paradiseduo** [comment]
> 1.6.4的超时设置也是5S吗？墙的可能性不大，因为即使软件显示订阅失败，在服务器端也可以查看到该时间的订阅记录，实际上是订阅成功的，我猜想由于网络质量及节点导致5S以后传输到端，所以会显示失败。也可能是我已经订阅到节点（已经自由），再手动更新订阅，在节点网络不好的情况下这个数据传输必然返回超过5S。建议评估国内网络不好的情况下在后版本延长超时时间？感谢答主~美好的软件

对的，5s是从1.6.4版本开始的，之前一直都是60s。

1.6.5跟1.6.4在订阅逻辑上只改了一个删除订阅时顺带删除该订阅下的所有节点，这个改动应该不会影响节点的订阅请求。

**Comment by paradiseduo** [comment]
1.6.7版本会加上 **更新订阅（通过代理）** 与 **更新订阅（不通过代理）** 的选项

**Comment by Mr-AlbertZhang** [comment]
> 1.6.7版本会加上 **更新订阅（通过代理）** 与 **更新订阅（不通过代理）** 的选项

感谢！
