### ISSUE TITLE
全局模式不可用；PAC模式正常

### ISSUE THREAD

**Issue by simohauml** [paradiseduo/ShadowsocksX-NG-R8#28]
**System and Shadowsocksx-NG-R8 version:**

- macOS 10.15.4 (19E287)
- Shadowsocksx-NG-R 1.6.2

**Actual behavior:**
全局模式下网络连接断开。用任何浏览器、连接任何页面失败。

**ss-local.log**
[ss-local.log](https://github.com/paradiseduo/ShadowsocksX-NG-R8/files/4570075/ss-local.log)

**Application log**

default	18:35:41.693058+0800	ShadowsocksX-NG	LSExceptions shared instance invalidated for timeout.

**Comment by paradiseduo** [comment]
你用PAC模式访问的墙外还是墙内的网站，全局不可用只可能是你节点挂掉了。

**Comment by simohauml** [comment]
PAC模式下墙内墙外都没问题。只要切换到Global模式，墙内外就都上不去。节点确认是可用的。我系统里还安装了ClashX、ClashXR、V2rayU，之前安装过ShadowsockeNG，后来卸载掉了。会不会被这些软件影响了？

**Comment by paradiseduo** [comment]
很有可能，因为很多软件的默认端口都是一样的，像V2rayU，默认也占用1086端口。
我看你的日志，1086端口有一段时间被占用：
```bash
2020-05-03 09:16:26 INFO: listening at 127.0.0.1:1086
 2020-05-03 09:23:07 ERROR: remote_recv_cb_recv: Connection reset by peer
 2020-05-03 09:35:42 ERROR: remote_recv_cb_recv: Connection reset by peer
 2020-05-03 09:35:54 ERROR: remote_recv_cb_recv: Connection reset by peer
 2020-05-03 10:46:52 ERROR: remote_recv_cb_recv: Connection reset by peer
 2020-05-03 13:16:41 ERROR: remote_recv_cb_recv: Connection reset by peer
 2020-05-03 15:16:41 ERROR: remote_recv_cb_recv: Connection reset by peer
 2020-05-03 15:32:30 ERROR: remote_recv_cb_recv: Connection reset by peer
 2020-05-03 15:32:30 ERROR: remote_recv_cb_recv: Connection reset by peer
 2020-05-03 15:32:41 ERROR: remote_recv_cb_recv: Connection reset by peer
```
而且PAC同一时间只能有一个代理软件设置的生效（但是大家用的都是一套东西，名单就那么几个）。
建议你看一下1086和1087端口是不是被别的程序占用了：
```bash
➜  lsof -i:1087
COMMAND    PID       USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
Google     998 x   19u  IPv4 0x52b7224f49c83e09      0t0  TCP localhost:51156->localhost:cplscrambler-in (ESTABLISHED)
Google     998 x   30u  IPv4 0x52b7224f40f10429      0t0  TCP localhost:51149->localhost:cplscrambler-in (CLOSE_WAIT)
privoxy   4803 x    3u  IPv4 0x52b7224f49c8d2c9      0t0  TCP localhost:cplscrambler-in (LISTEN)
privoxy   4803 x    4u  IPv4 0x52b7224f461768e9      0t0  TCP localhost:cplscrambler-in->localhost:51156 (ESTABLISHED)

➜  lsof -i:1086
COMMAND   PID       USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
ss-local 4799 x    8u  IPv4 0x52b7224f49c9aa49      0t0  TCP localhost:cplscrambler-lg (LISTEN)
ss-local 4799 x    9u  IPv4 0x52b7224f40f10e09      0t0  TCP localhost:cplscrambler-lg->localhost:51165 (ESTABLISHED)
privoxy  4803 x    5u  IPv4 0x52b7224f46184069      0t0  TCP localhost:51165->localhost:cplscrambler-lg (ESTABLISHED)
```

**Comment by simohauml** [comment]
确实，1087端口被v2rayu占用了。卸载v2rayu解决。多谢！

**Comment by Fomovet** [comment]
@paradiseduo @simohauml 遇到同样问题了，PAC模式正常访问Google，开启全局模式Chrome浏览器就出现网络连接断开，这里比较诡异的是Safari浏览器是能正常访问Google的，检查1086、1087这两个端口也没出现其他软件占用的情况～

**Comment by paradiseduo** [comment]
> @paradiseduo @simohauml 遇到同样问题了，PAC模式正常访问Google，开启全局模式Chrome浏览器就出现网络连接断开，这里比较诡异的是Safari浏览器是能正常访问Google的，检查1086、1087这两个端口也没出现其他软件占用的情况～

重启电脑，另外检查一下Chrome是否单独设置了代理。

**Comment by Fomovet** [comment]
@paradiseduo 我尝试按照前辈你说的步骤进行：关机重启、禁用所有Chrome浏览器插件、检测软件端口占用、节点连接的情况，还是没找到问题所在

**Comment by paradiseduo** [comment]
> @paradiseduo 我尝试按照前辈你说的步骤进行：关机重启、禁用所有Chrome浏览器插件、检测软件端口占用、节点连接的情况，还是没找到问题所在

开启全局代理，检查这三项是否是SSR设置的：
![image](https://user-images.githubusercontent.com/14846965/82523524-141f1080-9b5f-11ea-863c-7e52260710b1.png)

**Comment by Fomovet** [comment]
> > @paradiseduo 我尝试按照前辈你说的步骤进行：关机重启、禁用所有Chrome浏览器插件、检测软件端口占用、节点连接的情况，还是没找到问题所在
> 
> 开启全局代理，检查这三项是否是SSR设置的：
> ![image](https://user-images.githubusercontent.com/14846965/82523524-141f1080-9b5f-11ea-863c-7e52260710b1.png)

### 检查发现配置是没问题的，我截了一些图片：
<img width="1283" alt="2" src="https://user-images.githubusercontent.com/16652067/82524362-53e6f780-9b61-11ea-9a1c-9f7f9eb435a2.png">
<img width="681" alt="1" src="https://user-images.githubusercontent.com/16652067/82524370-58abab80-9b61-11ea-87ce-75e8fc2f7bdc.png">
<img width="642" alt="3" src="https://user-images.githubusercontent.com/16652067/82524377-5cd7c900-9b61-11ea-8084-fc009076d946.png">
<img width="718" alt="4" src="https://user-images.githubusercontent.com/16652067/82524381-606b5000-9b61-11ea-8d44-ddf8dcbafd8f.png">
<img width="1010" alt="5" src="https://user-images.githubusercontent.com/16652067/82524389-63664080-9b61-11ea-9459-7d51302a5bc5.png">
<img width="1332" alt="6" src="https://user-images.githubusercontent.com/16652067/82524445-8690f000-9b61-11ea-9f70-340b212d37dc.png">

**Comment by paradiseduo** [comment]
@Fomovet 装个SwitchyOmega吧
