### ISSUE TITLE
user rules for PAC 无效

### ISSUE THREAD

**Issue by moremoneylessproblem** [paradiseduo/ShadowsocksX-NG-R8#29]
1
**System and Shadowsocksx-NG-R8 version:**

- macOS 10.15.4 (19E287)
- Shadowsocksx-NG-R 1.6.2 当前系统显示1.6.5(1)

**Expected behavior:**
用户定义 PAC 规则定义后会自动刷新，但是并没有生效。

**Actual behavior:**
输入自定义规则后并没有添加到 proxy.pac 且该自定义规则未生效
(N/A for feature requests)

**Steps to reproduce:**

(N/A for feature requests)

**How often does this happen?**

(N/A for feature requests)

**ss-local.log**

Please upload the ss-local.log file here the file is in `~/Library/Logs`
1) Open 'Advanced Settings -> enable Verbose Mode'
2) Continue run `Shadowsocksx-NG-R` for 5 minutes
3) Upload the `~/Library/Logs/ss-local.log` here (with or without compress)

**Application log**

Open the `Console.app` and search `Shadowsocksx-NG-R8`
Copy paste the log here

**Crash Log**

If the app crashes and pop up a crash log, please copy and paste here

**Tips:**

- Always check for the latest update, some known bug has been fix in the latest release such as old version not support auth_aes_md5 auth_aes_sha1

- Beta version of macOS also may couse some problems

- ss-local compiled by macOS Sierra 10.12 not compatite with 10.11, some old release's ss-local are compiled using 10.12 will not work on 10.11, new release are try build in 10.10 to max fit the compatite

**Comment by paradiseduo** [comment]
你贴一下你加的规则，我明天调试一下看看

**Comment by moremoneylessproblem** [comment]
! Put user rules line by line in this file.
! See https://adblockplus.org/en/filter-cheatsheet
“||broadcom.com”,
“||broadcom.cn”,
“||ip138.com”, 这个网站用来查询当前 IP，走全局就是远程地址，走 PAC 就是本地地址。

**Comment by paradiseduo** [comment]
问题已修复，原因是没有刷新当前的PAC规则（虽然提示了），所以从127.0.0.1:8090端口下载的pac文件还是之前未修改过的，其实重启APP就可以。
现在已就改成每次改完用户规则就自动刷新。
另外用户自定义规则可以不加引号和逗号，只要换行就行了：
```bash
! Put user rules line by line in this file.
! See https://adblockplus.org/en/filter-cheatsheet
||discordapp.com
||discord.gg
||discord.media
||discordapp.net
||steampowered.com
||steamcommunity.com
||steamstatic.com
||store.steampowered.com
||ip138.com
||ipip.net
```

**Comment by moremoneylessproblem** [comment]
辛苦了，问题已解决。另外请问，PAC 文件和用户自定义文件的存储位置是否可以告知？

**Comment by paradiseduo** [comment]
> 辛苦了，问题已解决。另外请问，PAC 文件和用户自定义文件的存储位置是否可以告知？

```bash
➜ cd ~/.ShadowsocksX-NG
➜ ls 
backchn.acl         chn.acl             gfwlist.acl         gfwlist.js          gfwlist.txt         user-privoxy.config user-rule.txt
```
README里面已经写明路径了

**Comment by moremoneylessproblem** [comment]
我认真看了下readme.swift 和.md，没有找到这个部分，非常感谢你的解惑。另外还有个问题，我不知道github的私下联系方式只好继续在这里留言了。不知道你是否有制作windows版的计划？当前使用的shahdowsocksr 4.9.2 for windows并不好用。且已经无人回应issue了。

**Comment by paradiseduo** [comment]
> 我认真看了下readme.swift 和.md，没有找到这个部分，非常感谢你的解惑。另外还有个问题，我不知道github的私下联系方式只好继续在这里留言了。不知道你是否有制作windows版的计划？当前使用的shahdowsocksr 4.9.2 for windows并不好用。且已经无人回应issue了。

可以使用clash for windows
https://merlinblog.xyz/wiki/cfw.html
转换地址：
https://subto.herokuapp.com/sub?target=clashr&url=
https://sub.ops.ci/sub?target=clashr&url=

安全性问题自行考虑，当然也可以用我的subweb项目自己搭建一个转换器。
原版clash for windows不支持SSR，但是你可以直接下载支持SSR的clash内核替换掉原来的
