### ISSUE TITLE
macos 没有“从剪贴板导入代理”的选项

### ISSUE THREAD

**Issue by wangke8023** [paradiseduo/ShadowsocksX-NG-R8#30]
**System and Shadowsocksx-NG-R8 version:**

- Macos Mojave 版本 10.14.6
- Shadowsocksx-NG-R 1.6.5

**Expected behavior:**

  使用剪贴板导入代理链接
**Actual behavior:**

代理选择的选项卡中，没有“从剪贴板中导入”的选项
<img width="527" alt="屏幕快照 2020-05-04 23 02 56" src="https://user-images.githubusercontent.com/43570520/80980622-71c31580-8e5b-11ea-990d-8a8a3be90264.png">

**Comment by paradiseduo** [comment]
下个版本会修，改主菜单的时候不小心删掉了
