### ISSUE TITLE
同时勾选“应用设置”登录选项的四项，开机时自动更新失败。

### ISSUE THREAD

**Issue by Sam-Caesarmat** [paradiseduo/ShadowsocksX-NG-R8#31]
在不勾选“打开后自动连接”时，订阅更新**提示依次弹出**，可更新成功；
在勾选“打开后自动连接”后，关机前将小飞机翻墙模式关闭，全部更新失败，且更新失败的**提示同时弹出**。
在勾选“打开后自动连接”后，关机前依旧开启小飞机翻墙模式，部分订阅提示更新成功，但会提示下图所示内容，部分订阅提示更新失败（内包括被墙的的订阅与正常的订阅）**所有通知同时弹出**。
（测试时所使用的节点皆可正常使用）
![image](https://user-images.githubusercontent.com/42537544/81035253-c0f55e80-8ecc-11ea-9392-bbce9119fc93.png)
![image](https://user-images.githubusercontent.com/42537544/81035265-cf437a80-8ecc-11ea-86c5-ad5bde6d8143.png)

**Comment by paradiseduo** [comment]
<img width="302" alt="截屏2020-05-05 下午4 36 42" src="https://user-images.githubusercontent.com/14846965/81048295-a3d18780-8eee-11ea-8f51-4619e404b807.png">

<img width="340" alt="截屏2020-05-05 下午4 33 23" src="https://user-images.githubusercontent.com/14846965/81048102-3faec380-8eee-11ea-8fdc-7343210022a7.png">
我这边测了几遍，都可以正常更新订阅啊。
我这三个地址里有两个是被墙的。

**Comment by Sam-Caesarmat** [comment]
> 我这边测了几遍，都可以正常更新订阅啊。 我这三个地址里有两个是被墙的。

😭😭

**Comment by Sam-Caesarmat** [comment]
> <img alt="截屏2020-05-05 下午4 36 42" width="302" src="https://user-images.githubusercontent.com/14846965/81048295-a3d18780-8eee-11ea-8f51-4619e404b807.png">
> 
> <img alt="截屏2020-05-05 下午4 33 23" width="340" src="https://user-images.githubusercontent.com/14846965/81048102-3faec380-8eee-11ea-8fdc-7343210022a7.png">
> 
> 我这边测了几遍，都可以正常更新订阅啊。 我这三个地址里有两个是被墙的。

大佬，这个是开机时候的自动更新么，

**Comment by Sam-Caesarmat** [comment]
> 我这边测了几遍，都可以正常更新订阅啊。 我这三个地址里有两个是被墙的。

大佬，这个是开机时候的自动更新嘛😂😂

**Comment by paradiseduo** [comment]
> > 我这边测了几遍，都可以正常更新订阅啊。 我这三个地址里有两个是被墙的。
> 
> 大佬，这个是开机时候的自动更新嘛

是啊，重启电脑后更新的，试了三次都可以更新成功。
退出当前用户重新登录试了两次，也都可以更新成功。

**Comment by Sam-Caesarmat** [comment]
> > > 我这边测了几遍，都可以正常更新订阅啊。 我这三个地址里有两个是被墙的。
> > 
> > 
> > 大佬，这个是开机时候的自动更新嘛
> 
> 是啊，重启电脑后更新的，试了三次都可以更新成功。
> 退出当前用户重新登录试了两次，也都可以更新成功。

好吧😭

**Comment by DraculaPrince** [comment]
我这也有这个问题啊，同设置项，而且我点击“服务器延迟测试”，不会自动选中延迟最低的那个了。。以前在1.6.4和1.6.5上是可以选中的。

**Comment by paradiseduo** [comment]
> 我这也有这个问题啊，同设置项，而且我点击“服务器延迟测试”，不会自动选中延迟最低的那个了。。以前在1.6.4和1.6.5上是可以选中的。

我维护的分支从来没有自动选择节点的功能啊，而且自动选择节点的分支也没有1.6.4和1.6.5版本，你一定是穿越了🤣

**Comment by Sam-Caesarmat** [comment]
> 我这也有这个问题啊，同设置项，而且我点击“服务器延迟测试”，不会自动选中延迟最低的那个了。。以前在1.6.4和1.6.5上是可以选中的。

试试作者大佬的最新版本😂

**Comment by Sam-Caesarmat** [comment]
我印象中，好像从开始用小飞机，到现在不同的作者好像都有这个情况😂所以就一直没开那个选项，之后偶尔试过几次都没成功。😂

**Comment by paradiseduo** [comment]
> 我印象中，好像从开始用小飞机，到现在不同的作者好像都有这个情况😂所以就一直没开那个选项，之后偶尔试过几次都没成功。😂

下个版本会增加更新订阅（通过代理）和更新订阅（不通过代理）的选项，如果到时候两种都无法更新订阅，那就是网络的问题了。。

**Comment by Sam-Caesarmat** [comment]
> > 我印象中，好像从开始用小飞机，到现在不同的作者好像都有这个情况joy所以就一直没开那个选项，之后偶尔试过几次都没成功。joy
> 
> 下个版本会增加更新订阅（通过代理）和更新订阅（不通过代理）的选项，如果到时候两种都无法更新订阅，那就是网络的问题了。。

大佬辛苦了

**Comment by Sam-Caesarmat** [comment]
> > 我印象中，好像从开始用小飞机，到现在不同的作者好像都有这个情况😂所以就一直没开那个选项，之后偶尔试过几次都没成功。😂
> 
> 下个版本会增加更新订阅（通过代理）和更新订阅（不通过代理）的选项，如果到时候两种都无法更新订阅，那就是网络的问题了。。

大佬要不要加一下将小飞机图标和网速合并的选项😂😂

**Comment by paradiseduo** [comment]
version 1.6.7
至于合并图标的事情，暂时不在考虑范围内。。（之前的代码我都删了🤣，而且加回来会让代码的逻辑更复杂，更容易出问题）
