### ISSUE TITLE
最新版本支持obfs吗？

### ISSUE THREAD

**Issue by xem1987** [paradiseduo/ShadowsocksX-NG-R8#32]
现在最新版本是否支持obfs？
如何支持需要如何设置？

**Comment by paradiseduo** [comment]
支持simple-obfs

**Comment by paradiseduo** [comment]
你是指这个？

https://github.com/shadowsocksr-backup/shadowsocks-rss/wiki/obfs

**Comment by xem1987** [comment]
> 你是指这个？
> 
> 
> 
> https://github.com/shadowsocksr-backup/shadowsocks-rss/wiki/obfs

是的，里面好像没有obfs

**Comment by paradiseduo** [comment]
<img width="282" alt="BD4AA306-477F-41DC-B6EB-04968DD2E76D" src="https://user-images.githubusercontent.com/14846965/81059402-f0bf5900-8f02-11ea-8317-eb4f5a17fa4f.png">
这个不是吗？

**Comment by xem1987** [comment]
> <img alt="BD4AA306-477F-41DC-B6EB-04968DD2E76D" width="282" src="https://user-images.githubusercontent.com/14846965/81059402-f0bf5900-8f02-11ea-8317-eb4f5a17fa4f.png">
> 这个不是吗？

我也不是很清楚，尝试设置了一下都不行，机场给的只有obfs=tls，有点小白，不知道怎么设置，望赐教

**Comment by paradiseduo** [comment]
你首先要清楚机场提供的是SS还是SSR服务，SS用[这个](https://github.com/shadowsocks/ShadowsocksX-NG/releases)，我维护的版本是SSR的，不支持SS的一些新协议。

**Comment by xem1987** [comment]
是SS，对比app，是没有obfs插件，谢谢解答
