### ISSUE TITLE
How to bypass local addresses and domains?

### ISSUE THREAD

**Issue by parhamk** [paradiseduo/ShadowsocksX-NG-R8#33]

**Comment by paradiseduo** [comment]
Wirte those:
```bash
192.168.0.0/16, 10.0.0.0/8, 172.16.0.0/12, 127.0.0.1, localhost, *.local, timestamp.apple.com
```
To
![image](https://user-images.githubusercontent.com/14846965/81078588-06437b80-8f21-11ea-86d7-94839944c83b.png)

**Comment by parhamk** [comment]
@paradiseduo thank you.
the problem is they will not persist if you switch between **Manual** and **Global** mode.

it would be better if the user could maintain this list in the application itself. ShadowsocksX-NG had this feature.

**Comment by paradiseduo** [comment]
This feature will be added in later versions

**Comment by leechiuccc** [comment]
ACL自动模式应该就可以了吧，不过要改ACL名单

**Comment by Zykaz** [comment]
@paradiseduo Hi, I just wonder why I can't use it, it showed Error when I was trying to connect to any website, but if I turn off the HTTP Proxy feature, it just run like no problems...

BTW, the best SSR work, thanks you very very much for helping me use internet smoothly

P.S. I've completely remove NG-R8 1.4.4-r8 (`qinyuhang` version)

**Comment by paradiseduo** [comment]
> @paradiseduo Hi, I just wonder why I can't use it, it showed Error when I was trying to connect to any website, but if I turn off the HTTP Proxy feature, it just run like no problems...
> 
> BTW, the best SSR work, thanks you very very much for helping me use internet smoothly
> 
> P.S. I've completely remove NG-R8 1.4.4-r8 (`qinyuhang` version)


You may need to find all the folders or projects containing 'ShadowsocksX' under the path and delete them according to the way in README.md, and then install this version.

**Comment by Zykaz** [comment]
> > @paradiseduo Hi, I just wonder why I can't use it, it showed Error when I was trying to connect to any website, but if I turn off the HTTP Proxy feature, it just run like no problems...
> > BTW, the best SSR work, thanks you very very much for helping me use internet smoothly
> > P.S. I've completely remove NG-R8 1.4.4-r8 (`qinyuhang` version)
> 
> You may need to find all the folders or projects containing 'ShadowsocksX' under the path and delete them according to the way in README.md, and then install this version.

I'll try it, thanks !!

**EDIT :  Fixed !**
