### ISSUE TITLE
建议服务器设置打开时自动选择当前使用的服务器节点

### ISSUE THREAD

**Issue by xem1987** [paradiseduo/ShadowsocksX-NG-R8#34]
建议打开服务器设置时，自动选择当前选择的服务器节点配置，便于修改，调试

**Comment by paradiseduo** [comment]
你可以先导出所有节点做个备份，然后把用不到的节点删除啊。。🤔

调试完再导入回来。

**Comment by xem1987** [comment]
> 你可以先导出所有节点做个备份，然后把用不到的节点删除啊。。🤔
> 
> 调试完再导入回来。

是可以这么操作，所以只是建议

**Comment by paradiseduo** [comment]
> > 你可以先导出所有节点做个备份，然后把用不到的节点删除啊。。🤔
> > 调试完再导入回来。
> 
> 是可以这么操作，所以只是建议

我查了一下资料，虽然可以做到选中当前使用的服务器，但问题是NSTabelView是没有滚动动画的，也就是说如果当前使用的服务器在一页以外，那么NSTableView不会自动滚动到选中的那一行，这样给人的感觉就比较混乱。
因此只能保持当前的模式。
