### ISSUE TITLE
软件在开启一段时间之后延迟测试无效

### ISSUE THREAD

**Issue by ghost** [paradiseduo/ShadowsocksX-NG-R8#35]
软件开着大概一天之后延迟测试会失效,系统10.15.4,一定要退出软件重启才能测试延迟.另外每次更新完订阅都会自动选择列表最上面的一个节点,能否让其默认选择上次选的那个节点?

**Comment by paradiseduo** [comment]
测试延迟失效是ICMP和TCP都不能测吗？

**Comment by ghost** [comment]
目前知道是TCP不能测,下次再出现这个问题我试试ICMP

**Comment by paradiseduo** [comment]
更新完订阅默认选择上次选中的节点已经加上了，但是如果机场把你选择的节点删除了，你订阅之后还是会默认选择列表当中第一个节点。

**Comment by paradiseduo** [comment]
version 1.6.7
