### ISSUE TITLE
老哥能实现个快捷键功能不？🐶

### ISSUE THREAD

**Issue by agulado** [paradiseduo/ShadowsocksX-NG-R8#37]
![shortcuts](http://www.twedding.cn/shortcuts.jpg)
[捶腿][揉肩][跳舞]

**Comment by paradiseduo** [comment]
Next Version Feature: ShortCuts Support

**Comment by agulado** [comment]
是。气人就气人在他那个是全局的快捷键 😂，而且还能自己设置。
我主要是想全局的开关，切换模式并不是很重要。
不过我看有别的兄弟是想用快捷键切换模式～
老哥加油老哥～～～加🍗～～～

**Comment by agulado** [comment]
> Next Version Feature: ShortCuts Support

👍

**Comment by paradiseduo** [comment]
release 1.6.8
