### ISSUE TITLE
菜单优化建议

### ISSUE THREAD

**Issue by Scyllaly** [paradiseduo/ShadowsocksX-NG-R8#38]
- 状态
   - 启用 / 禁用
- 模式
   - PAC模式
   - 白名单模式
   - 全局模式
   -  ACL模式
       - ACL 自动
       - 代理大陆IP（这个是什么东东？跟白名单的区别？能否搞成 ，PAC 更新为 GFWLIST 、大陆常见域名及IP等）
- 服务器
   - 服务器列表
   - 延迟测试
   - 订阅列表
       - 订阅设置
       - 更新订阅
   - 导入
       - 从屏幕扫描导入
       - 从剪贴板导入
- 设置
   - 应用设置
   - 原有的“高级代理设置与HTTP代理设置”合并为一个 ，改名为：代理设置
   - 查看日志
   - 问题反馈
   - 检查更新
   - 关于
- 退出

**Comment by Scyllaly** [comment]
现有的 手动模式和 ACL 模式是什么

**Comment by paradiseduo** [comment]
* 目前PAC list就是[GFWLIST](https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt)
* ACL是更高级的PAC模式，具体区别可以自行查询（[#16 ](https://github.com/paradiseduo/ShadowsocksX-NG-R8/issues/16)）。
* 手动模式普通用户用不到(一般用到的人都知道手动模式是干啥的)。
* 白名单模式就是你说的绕过大陆IP。
* 代理大陆IP国内用不到，是国外用户为了访问国内网站用的，毕竟墙是双向的。也可以理解为大陆IP走代理，国外直连。
* 所有的规则默认更新地址都可以在`规则名单设置->规则更新设置`中看到，用的是[ACL4SSR](https://github.com/ACL4SSR/ACL4SSR)的规则
* 之前做过HTTP设置跟高级代理设置合到一起，但是有些逻辑问题需要处理(不是很好做，怕出问题)，所以就分开了。

**Comment by paradiseduo** [comment]
至于HTTP设置跟高级代理设置合到一起，之前也做过，但是有些逻辑问题需要处理(不是很好做，怕出问题)，所以就分开了。

**Comment by tabit2** [comment]
如果把`高级代理、http代理、规则更新设置、应用设置`合并为一个带多标签的设置窗口会不会好点？

另外注意到白名单也是通过软件分流的，干脆叫`PAC自动、ACL白名单、ACL自动、ACL回国、全局模式、手动模式`好了，如果觉得模式太多太乱，不妨像v2rayU那样，可以在设置中把用不到的模式隐藏起来

**Comment by paradiseduo** [comment]
> 如果把`高级代理、http代理、规则更新设置、应用设置`合并为一个带多标签的设置窗口会不会好点？
> 
> 另外注意到白名单也是通过软件分流的，干脆叫`PAC自动、ACL白名单、ACL自动、ACL回国、全局模式、手动模式`好了，如果觉得模式太多太乱，不妨像v2rayU那样，可以在设置中把用不到的模式隐藏起来

目前不考虑改变模式的名称，这些模式从软件开始开发到现在已经沿用了好几年(不管是r8还是原版的ng)，用户已经习惯了。
至于把设置合并到一页，工程量不小，短期内不好办了(毕竟还要搬砖吃饭😭)。

**Comment by paradiseduo** [comment]
release 1.6.9
