### ISSUE TITLE
请问命令行工具里怎么使用代理？

### ISSUE THREAD

**Issue by ChengYour** [paradiseduo/ShadowsocksX-NG-R8#39]
使用浏览器翻墙没问题，速度很快，但是在命令行工具里下载国外的 app 速度奇慢，应该是代理没有生效，请问如何设置呢？

**Comment by paradiseduo** [comment]
首先点击这里：
![image](https://user-images.githubusercontent.com/14846965/82115774-6c3cc800-9797-11ea-9ad7-d0bef6047535.png)
然后复制到终端里

**Comment by paradiseduo** [comment]
或许你应该先搜一下[Mac 让命令行走代理](https://www.jianshu.com/p/7c9de5f0ada1)以及[查看终端是否走了代理](https://blog.csdn.net/youshaoduo/article/details/87938186?)

**Comment by ChengYour** [comment]
> 或许你应该先搜一下[Mac 让命令行走代理](https://www.jianshu.com/p/7c9de5f0ada1)以及[查看终端是否走了代理](https://blog.csdn.net/youshaoduo/article/details/87938186?)

感谢大佬的回复，终于解决了
