### ISSUE TITLE
从剪切板导入多个ssr失败

### ISSUE THREAD

**Issue by TomYule** [paradiseduo/ShadowsocksX-NG-R8#4]
**System and Shadowsocksx-NG-R8 version:**
1.5.1
- macOS 10.12.4 beta (16E144f)
- Shadowsocksx-NG-R8 1.3.9-build4

**Expected behavior:**
ssr://NDUuMTQ0LjIuNTE6NTg3NzpvcmlnaW46cmM0OnBsYWluOmJHNWpiaTV2Y21jZ05YVjUvP29iZnNwYXJhbT0mcmVtYXJrcz02STZyNXBhdjU2ZVJRUSZncm91cD1URzVqYmk1dmNtYw,ssr://NDUuMTQ3LjIwMS4xNjg6NTg3NzpvcmlnaW46cmM0OnBsYWluOmJHNWpiaTV2Y21jZ05YVjUvP29iZnNwYXJhbT0mcmVtYXJrcz02STZyNXBhdjU2ZVJRZyZncm91cD1URzVqYmk1dmNtYw,ssr://ODUuMTE3LjIzNC45ODo1ODc3Om9yaWdpbjpyYzQ6cGxhaW46Ykc1amJpNXZjbWNnTlhWNS8_b2Jmc3BhcmFtPSZyZW1hcmtzPTZJNnI1cGF2NTZlUlF3Jmdyb3VwPVRHNWpiaTV2Y21j,ssr://NDUuMTQ0LjIuMTg2OjU4Nzc6b3JpZ2luOnJjNDpwbGFpbjpiRzVqYmk1dmNtY2dOWFY1Lz9vYmZzcGFyYW09JnJlbWFya3M9Nkk2cjVwYXY1NmVSUkEmZ3JvdXA9VEc1amJpNXZjbWM,ssr://NDUuMTQ3LjIwMC4yMzc6NTg3NzpvcmlnaW46cmM0OnBsYWluOmJHNWpiaTV2Y21jZ01uUmwvP29iZnNwYXJhbT0mcmVtYXJrcz02STZyNXBhdjU2ZVJTUSZncm91cD1URzVqYmk1dmNtYw,ssr://NDYuMTcuNDUuMTk0OjU4Nzc6b3JpZ2luOnJjNDpwbGFpbjpiRzVqYmk1dmNtY2dNblJsLz9vYmZzcGFyYW09JnJlbWFya3M9Nkk2cjVwYXY1NmVSU2cmZ3JvdXA9VEc1amJpNXZjbWM,ssr://MTkzLjM4LjUwLjIwNjo1ODc3Om9yaWdpbjpyYzQ6cGxhaW46Ykc1amJpNXZjbWNnTW5SbC8_b2Jmc3BhcmFtPSZyZW1hcmtzPTZJNnI1cGF2NTZlUlN3Jmdyb3VwPVRHNWpiaTV2Y21j,ssr://NDUuMTM2LjI0NC4yMDQ6NTg3NzpvcmlnaW46cmM0OnBsYWluOmJHNWpiaTV2Y21jZ01uUmwvP29iZnNwYXJhbT0mcmVtYXJrcz02STZyNXBhdjU2ZVJUQSZncm91cD1URzVqYmk1dmNtYw,ssr://MTM5LjI4LjIzNS4yNDM6NTg3NzpvcmlnaW46cmM0OnBsYWluOmJHNWpiaTV2Y21jZ00zRjYvP29iZnNwYXJhbT0mcmVtYXJrcz01clNiNXAySjU1LTJSUSZncm91cD1URzVqYmk1dmNtYw,ssr://MTM5LjI4LjIzNS44NDo1ODc3Om9yaWdpbjpyYzQ6cGxhaW46Ykc1amJpNXZjbWNnTTNGNi8_b2Jmc3BhcmFtPSZyZW1hcmtzPTVyU2I1cDJKNTUtMlJnJmdyb3VwPVRHNWpiaTV2Y21j,ssr://NDUuODIuMjU1LjExNTo1ODc3Om9yaWdpbjpyYzQ6cGxhaW46Ykc1amJpNXZjbWNnTTNGNi8_b2Jmc3BhcmFtPSZyZW1hcmtzPTVyU2I1cDJKNTUtMlJ3Jmdyb3VwPVRHNWpiaTV2Y21j,ssr://NDUuMTIuMTA5LjEzNDo1ODc3Om9yaWdpbjpyYzQ6cGxhaW46Ykc1amJpNXZjbWNnTTNGNi8_b2Jmc3BhcmFtPSZyZW1hcmtzPTVyU2I1cDJKNTUtMlNBJmdyb3VwPVRHNWpiaTV2Y21j

https://lncn.org/
这个站点提供的ssr
**Actual behavior:**

(N/A for feature requests)

**Steps to reproduce:**

(N/A for feature requests)

**How often does this happen?**

(N/A for feature requests)

**ss-local.log**

Please upload the ss-local.log file here the file is in `~/Library/Logs`
1) Open 'Advanced Settings -> enable Verbose Mode'
2) Continue run `Shadowsocksx-NG-R8` for 5 minutes
3) Upload the `~/Library/Logs/ss-local.log` here (with or without compress)

**Application log**

Open the `Console.app` and search `Shadowsocksx-NG`
Copy paste the log here

**Crash Log**

If the app crashes and pop up a crash log, please copy and paste here

**Tips:**
可以参考 
https://github.com/qinyuhang/ShadowsocksX-NG-R/releases
这个版本 批量导入
- Always check for the latest update, some known bug has been fix in the latest release such as old version not support auth_aes_md5 auth_aes_sha1

- Beta version of macOS also may couse some problems

- ss-local compiled by macOS Sierra 10.12 not compatite with 10.11, some old release's ss-local are compiled using 10.12 will not work on 10.11, new release are try build in 10.10 to max fit the compatite

**Comment by paradiseduo** [comment]
在1.5.2版本里会增加按逗号分隔多个SSR链接

**Comment by TomYule** [comment]
`ssr://NDUuMTQ0LjIuNTE6NTkzMzpvcmlnaW46cmM0OnBsYWluOmJHNWpiaTV2Y21jZ09HbHcvP29iZnNwYXJhbT0mcmVtYXJrcz02STZyNXBhdjU2ZVJRUSZncm91cD1URzVqYmk1dmNtYw,ssr://NDUuMTQ3LjIwMS4xNjg6NTkzMzpvcmlnaW46cmM0OnBsYWluOmJHNWpiaTV2Y21jZ09HbHcvP29iZnNwYXJhbT0mcmVtYXJrcz02STZyNXBhdjU2ZVJRZyZncm91cD1URzVqYmk1dmNtYw,ssr://ODUuMTE3LjIzNC45ODo1OTMzOm9yaWdpbjpyYzQ6cGxhaW46Ykc1amJpNXZjbWNnT0dsdy8_b2Jmc3BhcmFtPSZyZW1hcmtzPTZJNnI1cGF2NTZlUlF3Jmdyb3VwPVRHNWpiaTV2Y21j,ssr://NDUuMTQ0LjIuMTg2OjU5MzM6b3JpZ2luOnJjNDpwbGFpbjpiRzVqYmk1dmNtY2dPR2x3Lz9vYmZzcGFyYW09JnJlbWFya3M9Nkk2cjVwYXY1NmVSUkEmZ3JvdXA9VEc1amJpNXZjbWM,ssr://NDUuMTQ3LjIwMC4yMzc6NTkzMzpvcmlnaW46cmM0OnBsYWluOmJHNWpiaTV2Y21jZ01uSnkvP29iZnNwYXJhbT0mcmVtYXJrcz02STZyNXBhdjU2ZVJTUSZncm91cD1URzVqYmk1dmNtYw,ssr://NDYuMTcuNDUuMTk0OjU5MzM6b3JpZ2luOnJjNDpwbGFpbjpiRzVqYmk1dmNtY2dNbkp5Lz9vYmZzcGFyYW09JnJlbWFya3M9Nkk2cjVwYXY1NmVSU2cmZ3JvdXA9VEc1amJpNXZjbWM,ssr://MTkzLjM4LjUwLjIwNjo1OTMzOm9yaWdpbjpyYzQ6cGxhaW46Ykc1amJpNXZjbWNnTW5KeS8_b2Jmc3BhcmFtPSZyZW1hcmtzPTZJNnI1cGF2NTZlUlN3Jmdyb3VwPVRHNWpiaTV2Y21j,ssr://NDUuMTM2LjI0NC4yMDQ6NTkzMzpvcmlnaW46cmM0OnBsYWluOmJHNWpiaTV2Y21jZ01uSnkvP29iZnNwYXJhbT0mcmVtYXJrcz02STZyNXBhdjU2ZVJUQSZncm91cD1URzVqYmk1dmNtYw,ssr://MTM5LjI4LjIzNS4yNDM6NTkzMzpvcmlnaW46cmM0OnBsYWluOmJHNWpiaTV2Y21jZ01tcHAvP29iZnNwYXJhbT0mcmVtYXJrcz01clNiNXAySjU1LTJRUSZncm91cD1URzVqYmk1dmNtYw,ssr://MTM5LjI4LjIzNS44NDo1OTMzOm9yaWdpbjpyYzQ6cGxhaW46Ykc1amJpNXZjbWNnTW1wcC8_b2Jmc3BhcmFtPSZyZW1hcmtzPTVyU2I1cDJKNTUtMlFnJmdyb3VwPVRHNWpiaTV2Y21j,ssr://NDUuODIuMjU1LjExNTo1OTMzOm9yaWdpbjpyYzQ6cGxhaW46Ykc1amJpNXZjbWNnTW1wcC8_b2Jmc3BhcmFtPSZyZW1hcmtzPTVyU2I1cDJKNTUtMlF3Jmdyb3VwPVRHNWpiaTV2Y21j,ssr://NDUuMTIuMTA5LjEzNDo1OTMzOm9yaWdpbjpyYzQ6cGxhaW46Ykc1amJpNXZjbWNnTW1wcC8_b2Jmc3BhcmFtPSZyZW1hcmtzPTVyU2I1cDJKNTUtMlJBJmdyb3VwPVRHNWpiaTV2Y21j`
这个 批量导入 还是失败
版本1.5.4
系统版本  10.15.3

**Comment by paradiseduo** [comment]
> `ssr://NDUuMTQ0LjIuNTE6NTkzMzpvcmlnaW46cmM0OnBsYWluOmJHNWpiaTV2Y21jZ09HbHcvP29iZnNwYXJhbT0mcmVtYXJrcz02STZyNXBhdjU2ZVJRUSZncm91cD1URzVqYmk1dmNtYw,ssr://NDUuMTQ3LjIwMS4xNjg6NTkzMzpvcmlnaW46cmM0OnBsYWluOmJHNWpiaTV2Y21jZ09HbHcvP29iZnNwYXJhbT0mcmVtYXJrcz02STZyNXBhdjU2ZVJRZyZncm91cD1URzVqYmk1dmNtYw,ssr://ODUuMTE3LjIzNC45ODo1OTMzOm9yaWdpbjpyYzQ6cGxhaW46Ykc1amJpNXZjbWNnT0dsdy8_b2Jmc3BhcmFtPSZyZW1hcmtzPTZJNnI1cGF2NTZlUlF3Jmdyb3VwPVRHNWpiaTV2Y21j,ssr://NDUuMTQ0LjIuMTg2OjU5MzM6b3JpZ2luOnJjNDpwbGFpbjpiRzVqYmk1dmNtY2dPR2x3Lz9vYmZzcGFyYW09JnJlbWFya3M9Nkk2cjVwYXY1NmVSUkEmZ3JvdXA9VEc1amJpNXZjbWM,ssr://NDUuMTQ3LjIwMC4yMzc6NTkzMzpvcmlnaW46cmM0OnBsYWluOmJHNWpiaTV2Y21jZ01uSnkvP29iZnNwYXJhbT0mcmVtYXJrcz02STZyNXBhdjU2ZVJTUSZncm91cD1URzVqYmk1dmNtYw,ssr://NDYuMTcuNDUuMTk0OjU5MzM6b3JpZ2luOnJjNDpwbGFpbjpiRzVqYmk1dmNtY2dNbkp5Lz9vYmZzcGFyYW09JnJlbWFya3M9Nkk2cjVwYXY1NmVSU2cmZ3JvdXA9VEc1amJpNXZjbWM,ssr://MTkzLjM4LjUwLjIwNjo1OTMzOm9yaWdpbjpyYzQ6cGxhaW46Ykc1amJpNXZjbWNnTW5KeS8_b2Jmc3BhcmFtPSZyZW1hcmtzPTZJNnI1cGF2NTZlUlN3Jmdyb3VwPVRHNWpiaTV2Y21j,ssr://NDUuMTM2LjI0NC4yMDQ6NTkzMzpvcmlnaW46cmM0OnBsYWluOmJHNWpiaTV2Y21jZ01uSnkvP29iZnNwYXJhbT0mcmVtYXJrcz02STZyNXBhdjU2ZVJUQSZncm91cD1URzVqYmk1dmNtYw,ssr://MTM5LjI4LjIzNS4yNDM6NTkzMzpvcmlnaW46cmM0OnBsYWluOmJHNWpiaTV2Y21jZ01tcHAvP29iZnNwYXJhbT0mcmVtYXJrcz01clNiNXAySjU1LTJRUSZncm91cD1URzVqYmk1dmNtYw,ssr://MTM5LjI4LjIzNS44NDo1OTMzOm9yaWdpbjpyYzQ6cGxhaW46Ykc1amJpNXZjbWNnTW1wcC8_b2Jmc3BhcmFtPSZyZW1hcmtzPTVyU2I1cDJKNTUtMlFnJmdyb3VwPVRHNWpiaTV2Y21j,ssr://NDUuODIuMjU1LjExNTo1OTMzOm9yaWdpbjpyYzQ6cGxhaW46Ykc1amJpNXZjbWNnTW1wcC8_b2Jmc3BhcmFtPSZyZW1hcmtzPTVyU2I1cDJKNTUtMlF3Jmdyb3VwPVRHNWpiaTV2Y21j,ssr://NDUuMTIuMTA5LjEzNDo1OTMzOm9yaWdpbjpyYzQ6cGxhaW46Ykc1amJpNXZjbWNnTW1wcC8_b2Jmc3BhcmFtPSZyZW1hcmtzPTVyU2I1cDJKNTUtMlJBJmdyb3VwPVRHNWpiaTV2Y21j`
> 这个 批量导入 还是失败
> 版本1.5.4
> 系统版本 10.15.3


你是用的从文件导入还是从剪切板导入？我试了你的这个，从剪切板导入是正常的，请确保复制的文本中不包含多余的字符。
你要是从文件导入的话，那你这个格式不对，文件导入要用json格式。
文件内容像这样，并且保存成.json文件：
```
{
    "index": 0,
    "random": false,
    "global": false,
    "enabled": true,
    "shareOverLan": false,
    "isDefault": false,
    "localPort": 1080,
    "pacUrl": null,
    "useOnlinePac": false,
    "reconnectTimes": 3,
    "randomAlgorithm": 0,
    "TTL": 0,
    "proxyEnable": false,
    "proxyType": 0,
    "proxyHost": null,
    "proxyPort": 0,
    "proxyAuthUser": null,
    "proxyAuthPass": null,
    "authUser": null,
    "authPass": null,
    "autoban": false,
    "configs": [{
        "remarks": "example",
        "server": "abc.xyz",
        "server_port": 1234,
        "method": "rc4-md5",
        "obfs": "tls1.2_ticket_auth",
        "obfsparam": "baidu.com",
        "remarks_base64": "ZXhhbXBsZQ==",
        "password": "passwd",
        "tcp_over_udp": false,
        "udp_over_tcp": false,
        "protocol": "auth_sha1_v2",
        "obfs_udp": false,
        "enable": true
    },{
        "remarks": "example2",
        "server": "xyz.xyz",
        "server_port": 1234,
        "method": "rc4-md5",
        "obfs": "tls1.2_ticket_auth",
        "obfsparam": "baidu.com",
        "remarks_base64": "ZXhhbXBsZTI=",
        "password": "passwd",
        "tcp_over_udp": false,
        "udp_over_tcp": false,
        "protocol": "auth_sha1_v2",
        "obfs_udp": false,
        "enable": true
    }]
}
```

**Comment by TomYule** [comment]
那能不能再加一个 空格 分割  
合并一下 
https://github.com/qinyuhang/ShadowsocksX-NG-R/
master不好么

**Comment by paradiseduo** [comment]
> 那能不能再加一个 空格 分割
> 合并一下
> https://github.com/qinyuhang/ShadowsocksX-NG-R/
> master不好么

本项目是从原版的分支切出来的另行开发的，原版并没有从剪切板导入配置的功能哦。
另外我测试了一下，就算是存在空格也是可以识别的，就是用你上面复制的那些链接。
还是需要你再检查一下有没有包含特殊字符

**Comment by TomYule** [comment]
浏览器 导入 
`ssr://NDUuMTQ0LjIuNTE6NTkzMzpvcmlnaW46cmM0OnBsYWluOmJHNWpiaTV2Y21jZ09HbHcvP29iZnNwYXJhbT0mcmVtYXJrcz02STZyNXBhdjU2ZVJRUSZncm91cD1URzVqYmk1dmNtYw,ssr://NDUuMTQ3LjIwMS4xNjg6NTkzMzpvcmlnaW46cmM0OnBsYWluOmJHNWpiaTV2Y21jZ09HbHcvP29iZnNwYXJhbT0mcmVtYXJrcz02STZyNXBhdjU2ZVJRZyZncm91cD1URzVqYmk1dmNtYw,ssr://ODUuMTE3LjIzNC45ODo1OTMzOm9yaWdpbjpyYzQ6cGxhaW46Ykc1amJpNXZjbWNnT0dsdy8_b2Jmc3BhcmFtPSZyZW1hcmtzPTZJNnI1cGF2NTZlUlF3Jmdyb3VwPVRHNWpiaTV2Y21j,ssr://NDUuMTQ0LjIuMTg2OjU5MzM6b3JpZ2luOnJjNDpwbGFpbjpiRzVqYmk1dmNtY2dPR2x3Lz9vYmZzcGFyYW09JnJlbWFya3M9Nkk2cjVwYXY1NmVSUkEmZ3JvdXA9VEc1amJpNXZjbWM,ssr://NDUuMTQ3LjIwMC4yMzc6NTkzMzpvcmlnaW46cmM0OnBsYWluOmJHNWpiaTV2Y21jZ01uSnkvP29iZnNwYXJhbT0mcmVtYXJrcz02STZyNXBhdjU2ZVJTUSZncm91cD1URzVqYmk1dmNtYw,ssr://NDYuMTcuNDUuMTk0OjU5MzM6b3JpZ2luOnJjNDpwbGFpbjpiRzVqYmk1dmNtY2dNbkp5Lz9vYmZzcGFyYW09JnJlbWFya3M9Nkk2cjVwYXY1NmVSU2cmZ3JvdXA9VEc1amJpNXZjbWM,ssr://MTkzLjM4LjUwLjIwNjo1OTMzOm9yaWdpbjpyYzQ6cGxhaW46Ykc1amJpNXZjbWNnTW5KeS8_b2Jmc3BhcmFtPSZyZW1hcmtzPTZJNnI1cGF2NTZlUlN3Jmdyb3VwPVRHNWpiaTV2Y21j,ssr://NDUuMTM2LjI0NC4yMDQ6NTkzMzpvcmlnaW46cmM0OnBsYWluOmJHNWpiaTV2Y21jZ01uSnkvP29iZnNwYXJhbT0mcmVtYXJrcz02STZyNXBhdjU2ZVJUQSZncm91cD1URzVqYmk1dmNtYw,ssr://MTM5LjI4LjIzNS4yNDM6NTkzMzpvcmlnaW46cmM0OnBsYWluOmJHNWpiaTV2Y21jZ01tcHAvP29iZnNwYXJhbT0mcmVtYXJrcz01clNiNXAySjU1LTJRUSZncm91cD1URzVqYmk1dmNtYw,ssr://MTM5LjI4LjIzNS44NDo1OTMzOm9yaWdpbjpyYzQ6cGxhaW46Ykc1amJpNXZjbWNnTW1wcC8_b2Jmc3BhcmFtPSZyZW1hcmtzPTVyU2I1cDJKNTUtMlFnJmdyb3VwPVRHNWpiaTV2Y21j,ssr://NDUuODIuMjU1LjExNTo1OTMzOm9yaWdpbjpyYzQ6cGxhaW46Ykc1amJpNXZjbWNnTW1wcC8_b2Jmc3BhcmFtPSZyZW1hcmtzPTVyU2I1cDJKNTUtMlF3Jmdyb3VwPVRHNWpiaTV2Y21j,ssr://NDUuMTIuMTA5LjEzNDo1OTMzOm9yaWdpbjpyYzQ6cGxhaW46Ykc1amJpNXZjbWNnTW1wcC8_b2Jmc3BhcmFtPSZyZW1hcmtzPTVyU2I1cDJKNTUtMlJBJmdyb3VwPVRHNWpiaTV2Y21j`
被V2RAYU 占用了  这个如何解决呢

**Comment by TomYule** [comment]
执行了 各种删除 命令 现在 导入是没有问题了
版本号也对了   莫名其妙  又变了

**Comment by TomYule** [comment]
执行了 各种删除 命令 现在 导入是没有问题了
版本号也对了   莫名其妙  又变了

**Comment by paradiseduo** [comment]
> 浏览器 导入
> `ssr://NDUuMTQ0LjIuNTE6NTkzMzpvcmlnaW46cmM0OnBsYWluOmJHNWpiaTV2Y21jZ09HbHcvP29iZnNwYXJhbT0mcmVtYXJrcz02STZyNXBhdjU2ZVJRUSZncm91cD1URzVqYmk1dmNtYw,ssr://NDUuMTQ3LjIwMS4xNjg6NTkzMzpvcmlnaW46cmM0OnBsYWluOmJHNWpiaTV2Y21jZ09HbHcvP29iZnNwYXJhbT0mcmVtYXJrcz02STZyNXBhdjU2ZVJRZyZncm91cD1URzVqYmk1dmNtYw,ssr://ODUuMTE3LjIzNC45ODo1OTMzOm9yaWdpbjpyYzQ6cGxhaW46Ykc1amJpNXZjbWNnT0dsdy8_b2Jmc3BhcmFtPSZyZW1hcmtzPTZJNnI1cGF2NTZlUlF3Jmdyb3VwPVRHNWpiaTV2Y21j,ssr://NDUuMTQ0LjIuMTg2OjU5MzM6b3JpZ2luOnJjNDpwbGFpbjpiRzVqYmk1dmNtY2dPR2x3Lz9vYmZzcGFyYW09JnJlbWFya3M9Nkk2cjVwYXY1NmVSUkEmZ3JvdXA9VEc1amJpNXZjbWM,ssr://NDUuMTQ3LjIwMC4yMzc6NTkzMzpvcmlnaW46cmM0OnBsYWluOmJHNWpiaTV2Y21jZ01uSnkvP29iZnNwYXJhbT0mcmVtYXJrcz02STZyNXBhdjU2ZVJTUSZncm91cD1URzVqYmk1dmNtYw,ssr://NDYuMTcuNDUuMTk0OjU5MzM6b3JpZ2luOnJjNDpwbGFpbjpiRzVqYmk1dmNtY2dNbkp5Lz9vYmZzcGFyYW09JnJlbWFya3M9Nkk2cjVwYXY1NmVSU2cmZ3JvdXA9VEc1amJpNXZjbWM,ssr://MTkzLjM4LjUwLjIwNjo1OTMzOm9yaWdpbjpyYzQ6cGxhaW46Ykc1amJpNXZjbWNnTW5KeS8_b2Jmc3BhcmFtPSZyZW1hcmtzPTZJNnI1cGF2NTZlUlN3Jmdyb3VwPVRHNWpiaTV2Y21j,ssr://NDUuMTM2LjI0NC4yMDQ6NTkzMzpvcmlnaW46cmM0OnBsYWluOmJHNWpiaTV2Y21jZ01uSnkvP29iZnNwYXJhbT0mcmVtYXJrcz02STZyNXBhdjU2ZVJUQSZncm91cD1URzVqYmk1dmNtYw,ssr://MTM5LjI4LjIzNS4yNDM6NTkzMzpvcmlnaW46cmM0OnBsYWluOmJHNWpiaTV2Y21jZ01tcHAvP29iZnNwYXJhbT0mcmVtYXJrcz01clNiNXAySjU1LTJRUSZncm91cD1URzVqYmk1dmNtYw,ssr://MTM5LjI4LjIzNS44NDo1OTMzOm9yaWdpbjpyYzQ6cGxhaW46Ykc1amJpNXZjbWNnTW1wcC8_b2Jmc3BhcmFtPSZyZW1hcmtzPTVyU2I1cDJKNTUtMlFnJmdyb3VwPVRHNWpiaTV2Y21j,ssr://NDUuODIuMjU1LjExNTo1OTMzOm9yaWdpbjpyYzQ6cGxhaW46Ykc1amJpNXZjbWNnTW1wcC8_b2Jmc3BhcmFtPSZyZW1hcmtzPTVyU2I1cDJKNTUtMlF3Jmdyb3VwPVRHNWpiaTV2Y21j,ssr://NDUuMTIuMTA5LjEzNDo1OTMzOm9yaWdpbjpyYzQ6cGxhaW46Ykc1amJpNXZjbWNnTW1wcC8_b2Jmc3BhcmFtPSZyZW1hcmtzPTVyU2I1cDJKNTUtMlJBJmdyb3VwPVRHNWpiaTV2Y21j`
> 被V2RAYU 占用了 这个如何解决呢

v2ray默认也占用1086端口，你改一下呗。
