### ISSUE TITLE
[feat req] 通过shell命令编辑配置

### ISSUE THREAD

**Issue by j1ng** [paradiseduo/ShadowsocksX-NG-R8#40]
能否增加常用操作的shell命令 (或者扩展proxy_conf_helper)? 
例如: 通过shell命令编辑订阅, 编辑服务器配置等, 
或者能通过命令行加载配置文件(**替换**而非新增或合并)也行.
目的是能与其他脚本配合, 自动更新并去除无效配置.
最好还能增加触发更新订阅, 开始测速等命令
(新版本的快捷键很不错, 主要侧重的代理模式切换吧)

ps: 版本更新真勤快, 辛苦大佬了👍

**System and Shadowsocksx-NG-R8 version:**
- macOS 10.15.3 (19D76)
- Shadowsocksx-NG-R 1.6.7

**Comment by paradiseduo** [comment]
我认为这个功能在Mac上很难实现。

虽然proxy_conf_helper与APP打包在一起，但是他们是两个完全独立运行的程序，APP可以调用命令行程序是因为系统有专门的类可以实现该功能。
如果想用命令行调用APP的某些功能，目前我不清楚应该如何实现。

或者说你有现成的开源项目让我研究一下吗？
除非可以给出可行的方案，否则这些功能是无法实现的。

**Comment by paradiseduo** [comment]
目前已经有些头绪，但是鉴于该需求面向的用户很少，打算出一个Pro版本，把这个功能放在里面

**Comment by paradiseduo** [comment]
目前已经有些头绪，但是鉴于该需求面向的用户很少，打算出一个Pro版本，把这个功能放在里面
