### ISSUE TITLE
手动添加节点问题

### ISSUE THREAD

**Issue by Sam-Caesarmat** [paradiseduo/ShadowsocksX-NG-R8#41]
这两天刚发现一个问题：在更新订阅后，单独添加进去的节点就没了（昨天发的最新版也是这样）；如果在更新订阅后再次重新添加该节点，在服务器列表内会出现两个重复的节点。

**Comment by paradiseduo** [comment]
我这边测试是正常的啊
![屏幕快照 2020-06-01 下午12 45 36](https://user-images.githubusercontent.com/14846965/83376704-d8f5ca80-a405-11ea-8c21-f2d175a55ae5.png)

**Comment by Sam-Caesarmat** [comment]
😢

**Comment by paradiseduo** [comment]
你是不是节点的命名重复了？

**Comment by Sam-Caesarmat** [comment]
> 你是不是节点的命名重复了？

没啊，就这一个
![image](https://user-images.githubusercontent.com/42537544/83378628-db5b2300-a40b-11ea-8d7f-54d550d0c50d.png)

**Comment by Sam-Caesarmat** [comment]
之前还好好的，就是从两三天前开始这样，我也不知道为啥😑

**Comment by paradiseduo** [comment]
手动删除全部节点，然后再加一次试试

**Comment by Sam-Caesarmat** [comment]
> 手动删除全部节点，然后再加一次试试

还是这样，而且再重新从剪切板导入，一次性导入俩   😂
![image](https://user-images.githubusercontent.com/42537544/83386270-57119b80-a41d-11ea-8e1f-65f7786bbf15.png)

**Comment by Sam-Caesarmat** [comment]
对了，测速有时候是红色的但可以上网，但在shadowrocket上也可以ping通并且测出来只有二十多毫秒，也都是TCP测试😂

**Comment by paradiseduo** [comment]
> 对了，测速有时候是红色的但可以上网，但在shadowrocket上也可以ping通并且测出来只有二十多毫秒，也都是TCP测试😂

这个很正常，tcping的原理是建立socket链接，有时节点多了会导致测试超时（因为测速没分组，同时建立大量socket链接可能会出问题）。
另外小火箭不开源，他们有可能重写了SSR的底层库，在底层增加了测速的功能。

**Comment by Sam-Caesarmat** [comment]
> > 对了，测速有时候是红色的但可以上网，但在shadowrocket上也可以ping通并且测出来只有二十多毫秒，也都是TCP测试😂
> 
> 这个很正常，tcping的原理是建立socket链接，有时节点多了会导致测试超时（因为测速没分组，同时建立大量socket链接可能会出问题）。
> 另外小火箭不开源，他们有可能重写了SSR的底层库，在底层增加了测速的功能。

好叭，那之前那个问题是不是个bug😂

**Comment by paradiseduo** [comment]
估计是之前添加节点的时候出问题了，你可以清空缓存重新添加一次：
```bash
❯ cd ~/Library/Preferences
❯ rm -rf com.qiuyuzhou.ShadowsocksX-NG.plist
```
重启电脑
重新打开软件，添加订阅，添加节点

**Comment by Sam-Caesarmat** [comment]
> 估计是之前添加节点的时候出问题了，你可以清空缓存重新添加一次：
> 
> ```shell
> ❯ cd ~/Library/Preferences
> ❯ rm -rf com.qiuyuzhou.ShadowsocksX-NG.plist
> ```
> 
> 重启电脑
> 重新打开软件，添加订阅，添加节点

是这样么😂
![image](https://user-images.githubusercontent.com/42537544/83513395-4d169800-a504-11ea-9636-703717cee0df.png)
感觉我好想找不着...把前面那个箭头删掉再找也是找不到文件夹😢
第一行的那个，输入进去对话框消失了，没反应，可能是我太菜了🤣

**Comment by paradiseduo** [comment]
这是命令行啊。而且plist不是文件夹，是文件。
如果你只会用界面操作的话，那你输入`~/Library/Preferences`，然后找到com.qiuyuzhou.ShadowsocksX-NG.plist文件，右键删除。
