### ISSUE TITLE
ssr能否添加ss的服务器？

### ISSUE THREAD

**Issue by owenzhao** [paradiseduo/ShadowsocksX-NG-R8#43]
目前，ssr和ss的客户端是两个不同的软件。可问题是，它们两个某个部分是冲突的。表现为，如果一直使用其中的一个，比如ssr，那么只有第一次时会提示管理员权限，之后就可以正常使用了。

但是如果是混合使用，用过一个，再用另外一个的时候，就会再次要求输入密码，使用管理员权限。

如果ssr可以添加ss的设置，就像iOS下的小火箭那样，支持多种协议。就不需要经常切换了。

**Comment by paradiseduo** [comment]
可以使用ClashXR

**Comment by paradiseduo** [comment]
ss跟ssr底层库不同，同时支持需要将两个库全部引入，会增加安装包的体积，对于不挂代理直接下载的用户仅靠10kb的网速要下载很久。
就目前来看，SSR基本都是机场主在使用，很少有机场提供SS服务（目前SS流量会被精准识别）。
个人认为目前最好的方案是使用trojan，模拟真实的HTTPS流量。
V2ray的WebSocket+TLS+Web方案也可以，但是前两天刚出了漏洞，流量包含固定特征，因此V2ray目前处于重构状态，期待重构之后会更好。
