### ISSUE TITLE
【高级代理设置】无法修改【忽略这些主机与域的代理设置】

### ISSUE THREAD

**Issue by TakeshiKuranari** [paradiseduo/ShadowsocksX-NG-R8#44]
- macOS 10.15.5
- Shadowsocksx-NG-R 1.6.8

修改后按【确认】保存没有生效：再次进入该菜单，配置被还原

**Comment by paradiseduo** [comment]
你更新到最新版本试一试，另外【忽略这些主机与域的代理设置】在PAC模式和手动模式下不生效（有意为之，不是Bug）。
