### ISSUE TITLE
[建议]建议在订阅设置界面增加关键词过滤功能

### ISSUE THREAD

**Issue by coudser** [paradiseduo/ShadowsocksX-NG-R8#45]
ShadowSocksX-NG-R
建议在新增订阅设置的时候 ，增加一个过滤选项 ，可以根据关键词过滤出需要添加的节点。@wzdnzd版本已经实现该功能 ，希望贵方能加入 
<img width="480" alt="BE200B49-3755-49EF-ABF1-3F2E7F848CB4" src="https://user-images.githubusercontent.com/66861134/84561060-f28b0080-ad7b-11ea-90f5-6911b6e3da36.png">

**Comment by coudser** [comment]
实现结果如下
<img width="631" alt="A4D7CFBB-9A1B-4B16-8C5A-CD09FD2B2AE3" src="https://user-images.githubusercontent.com/66861134/84561103-2cf49d80-ad7c-11ea-8141-a0ceca860ee4.png">
真诚希望能优化加入 ，尤其在拥有 30+以上订阅节点情况下
过滤规则可以是 : 
方案1 ：包含特定关键词节点自动增加
方案2 ：排除特定关键词

**Comment by paradiseduo** [comment]
下个版本会加：
过滤含有特定关键词的节点
