### ISSUE TITLE
1.6.9 功能性闪退

### ISSUE THREAD

**Issue by Scyllaly** [paradiseduo/ShadowsocksX-NG-R8#46]
打开 程序，点电脑右上角小飞机图标 -》 服务器 -》 服务器设置 ，在弹出的添加服务器窗口中，点 + 号，然后点取消，整个应用直接闪退

**Comment by Scyllaly** [comment]
2.打开 程序，点电脑右上角小飞机图标 -》 服务器 -》 服务器设置 ，在弹出的添加服务器窗口中，点 + 号（未填入任何内容），然后点击复制，再点 - 号，再点加号时整个 服务器设置框 空白跳动，无法正确添加配置

**Comment by paradiseduo** [comment]
闪退问题已经定位，下个版本修复。
第二个问题没复现，但是这里确实有问题，体现在菜单的服务器列表里面，点击复制的时候会刷新服务器列表，讲道理应该是点`确认`的时候才刷新。
