### ISSUE TITLE
当有两个同一家机场订阅链接的时候，即便是修改了订阅链接的名称，新的也会覆盖旧的。

### ISSUE THREAD

**Issue by wang93wei** [paradiseduo/ShadowsocksX-NG-R8#47]
当有两个同一家机场订阅链接的时候，即便是修改了组名，新的也会覆盖旧的。
![image](https://user-images.githubusercontent.com/6371053/84583668-8bc61f80-ae2d-11ea-8b99-95b52251f867.png)
![image](https://user-images.githubusercontent.com/6371053/84583669-92549700-ae2d-11ea-8685-ed637455f665.png)

**Comment by paradiseduo** [comment]
两个订阅链接的节点是相同的吗

**Comment by wang93wei** [comment]
> 两个订阅链接的节点是相同的吗

不同，但是主域名都是一个。

**Comment by paradiseduo** [comment]
那就没问题啊，节点没覆盖，只是合并到同一个组里了。
这里组名的逻辑是如果机场没设置组名，那么就按你设置的来，如果他设置了组名，就会按机场的来。

**Comment by wang93wei** [comment]
> 那就没问题啊，节点没覆盖，只是合并到同一个组里了。
> 这里组名的逻辑是如果机场没设置组名，那么就按你设置的来，如果他设置了组名，就会按机场的来。

哦哦，懂了，不能单独成一组么？就是，自己手动修改组名，不按照机场的来

**Comment by paradiseduo** [comment]
挺难改的，里面有些复杂的逻辑，暂时不考虑改了，而且一般机场也就一个订阅连接
