### ISSUE TITLE
检查更新地址是 https://github.com/wzdnzd/ShadowsocksX-NG-R/releases

### ISSUE THREAD

**Issue by TomYule** [paradiseduo/ShadowsocksX-NG-R8#5]
**System and Shadowsocksx-NG-R8 version:**

- macOS 10.12.4 beta (16E144f)
- Shadowsocksx-NG-R8 1.3.9-build4

**Expected behavior:**

**Actual behavior:**

(N/A for feature requests)

**Steps to reproduce:**

(N/A for feature requests)

**How often does this happen?**

(N/A for feature requests)

**ss-local.log**

Please upload the ss-local.log file here the file is in `~/Library/Logs`
1) Open 'Advanced Settings -> enable Verbose Mode'
2) Continue run `Shadowsocksx-NG-R8` for 5 minutes
3) Upload the `~/Library/Logs/ss-local.log` here (with or without compress)

**Application log**

Open the `Console.app` and search `Shadowsocksx-NG`
Copy paste the log here

**Crash Log**

If the app crashes and pop up a crash log, please copy and paste here

**Tips:**

- Always check for the latest update, some known bug has been fix in the latest release such as old version not support auth_aes_md5 auth_aes_sha1

- Beta version of macOS also may couse some problems

- ss-local compiled by macOS Sierra 10.12 not compatite with 10.11, some old release's ss-local are compiled using 10.12 will not work on 10.11, new release are try build in 10.10 to max fit the compatite

**Comment by paradiseduo** [comment]
你升级到最新版1.5.1就没问题了

**Comment by TomYule** [comment]
虽然不知道为什么不一起维护一个项目 但是 还是希望双方都多借鉴彼此的 优秀的地方

**Comment by TomYule** [comment]
我就是下载最新的 1.5.1

**Comment by paradiseduo** [comment]
> 我就是下载最新的 1.5.1

我看了一下最新的代码，没有搜到这个地址，要不你直接删除再装一遍？不要覆盖安装。

**Comment by TomYule** [comment]
删除了 新安装的 1.5.4
系统版本 10.15.3
更新地址 还是如题

**Comment by paradiseduo** [comment]
> 删除了 新安装的 1.5.4
> 系统版本 10.15.3
> 更新地址 还是如题

上线前我都经过测试的，可以确保跳转的地址正确，你看一下是不是开错了软件。
另外下载地址是写死在代码里的，没有从配置文件中读取，因此代码中不存在这个地址，那么一定不会跳转到这个地址。

**Comment by TomYule** [comment]
我把 该删除的都删除了 检查更新 还是 同样的地址 关于 也是

**Comment by paradiseduo** [comment]
> 我把 该删除的都删除了 检查更新 还是 同样的地址 关于 也是

那说明你APP没开对啊。。我这边三台Mac，从github release下载的zip包，解压安装打开后都没问题，版本如下：
![image](https://user-images.githubusercontent.com/14846965/77391353-811e6000-6dd3-11ea-8173-910c2c790768.png)

**Comment by TomYule** [comment]
![image](https://user-images.githubusercontent.com/13266764/77392947-0e16e880-6dd7-11ea-997a-143bc0b4eb46.png)
