### ISSUE TITLE
启动软件会弹出恶意软件的提示

### ISSUE THREAD

**Issue by wang93wei** [paradiseduo/ShadowsocksX-NG-R8#50]
![image](https://user-images.githubusercontent.com/6371053/84847833-8b739180-b084-11ea-8be6-a84ea3bff36b.png)

是不是证书什么的过期了啊。。。
系统：10.15.5 (19F101)

**Comment by paradiseduo** [comment]
可能要考虑换一种方式安装helper了，10.5.5系统对证书校验变严格了。
我重新上传了一份，你下载试试。

**Comment by wang93wei** [comment]
> 可能要考虑换一种方式安装helper了，10.5.5系统对证书校验变严格了。
> 我重新上传了一份，你下载试试。

我刚刚下了一个1.70版本的，还是不行
![image](https://user-images.githubusercontent.com/6371053/84857224-22e3df00-b09b-11ea-8593-77facda8280b.png)

**Comment by paradiseduo** [comment]
你在系统偏好设置中开启允许任何来源了吗（不明白的话，百度一下你就知道）：
```bash
sudo spctl –master-disable
```
另外你需要先把软件移动到`应用程序`文件夹里面再打开

**Comment by wang93wei** [comment]
> 允许任何来源



> 你在系统偏好设置中开启允许任何来源了吗（不明白的话，百度一下你就知道）：
> 
> ```shell
> sudo spctl –master-disable
> ```
> 
> 另外你需要先把软件移动到`应用程序`文件夹里面再打开

开了，，，还是不行
![image](https://user-images.githubusercontent.com/6371053/84883858-a5809480-b0c3-11ea-8dc8-7d8feddc26c5.png)

我整体完整卸载一遍软件吧

**Comment by wang93wei** [comment]
彻底卸载解决了


可能是以前其他人改的版本的我都是直接覆盖导致现在就不行了
