### ISSUE TITLE
“proxy_conf_helper” 将对您的电脑造成伤害。

### ISSUE THREAD

**Issue by fraee** [paradiseduo/ShadowsocksX-NG-R8#52]
**System and Shadowsocksx-NG-R8 version:**

- macOS 10.15.5
- Shadowsocksx-NG-R 1.7.0

![1](https://user-images.githubusercontent.com/12388357/84995543-b3472000-b17e-11ea-8e8d-88fdb2ff0db5.png)

**Comment by Edisonnnshc** [comment]
我是1.9.4 遇到同样的问题 不知道怎么解决

**Comment by joiller** [comment]
我是按照readme里说的把东西删光了再开，就好了
还有设置里面开机自动启动也不能开，会弹类似的窗口。
macOS 10.15.5
Shadowsocksx-NG-R 1.7.0

**Comment by paradiseduo** [comment]
1、打开终端
2、把你想要打开的软件拖入这行代码后面，记住有个空格隔开
```bash 
sudo xattr -rd com.apple.quarantine 
```
3、完整命令就像这样
```bash
sudo xattr -rd com.apple.quarantine /Library/Application\ Support/ShadowsocksX-NG-R8/proxy_conf_helper
```
4、回车输入管理员密码
5、ok，执行完成
