### ISSUE TITLE
网速显示问题

### ISSUE THREAD

**Issue by Sam-Caesarmat** [paradiseduo/ShadowsocksX-NG-R8#53]
更新至macOS Big Sur 11.0 Beta版后 ShadowsocksX-NG-R8的网速显示有点偏上被上部挡住了一小部分（与右侧的clash显示的网速对比）
![image](https://user-images.githubusercontent.com/42537544/85377790-2a5c2a00-b56c-11ea-8b02-28aca02146a4.png)

还有，间隔有点大😂

**Comment by paradiseduo** [comment]
Beta版本不考虑适配，等正式版吧，很多问题其实是系统Bug。
