### ISSUE TITLE
1.7.0点击应用设置，闪退

### ISSUE THREAD

**Issue by DraculaPrince** [paradiseduo/ShadowsocksX-NG-R8#54]
**System and Shadowsocksx-NG-R8 version:**

- macOS 10.15.5
- Shadowsocksx-NG-R 1.7.0

**Expected behavior:**

**Actual behavior:**
新下载1.7.0，安全删除之前的版本，并且按照首页说明进行rm -rf删除诸项；
安装1.7.0后，点击打开翻墙并且扫描屏幕二维码录入；点击应用设置，直接闪退；
如此操作两次依然如此
(N/A for feature requests)

**Steps to reproduce:**

(N/A for feature requests)

**How often does this happen?**

(N/A for feature requests)

**ss-local.log**

Please upload the ss-local.log file here the file is in `~/Library/Logs`
1) Open 'Advanced Settings -> enable Verbose Mode'
2) Continue run `Shadowsocksx-NG-R` for 5 minutes
3) Upload the `~/Library/Logs/ss-local.log` here (with or without compress)

**Application log**

Open the `Console.app` and search `Shadowsocksx-NG-R8`
Copy paste the log here

**Crash Log**

If the app crashes and pop up a crash log, please copy and paste here

**Tips:**

- Always check for the latest update, some known bug has been fix in the latest release such as old version not support auth_aes_md5 auth_aes_sha1

- Beta version of macOS also may couse some problems

- ss-local compiled by macOS Sierra 10.12 not compatite with 10.11, some old release's ss-local are compiled using 10.12 will not work on 10.11, new release are try build in 10.10 to max fit the compatite

**Comment by paradiseduo** [comment]
你点击查看日志，然后重新操作一遍，把日志截图发一下，我这边没有复现，无法定位问题。

**Comment by DraculaPrince** [comment]
你必须要先‘开启’（此时里面没有节点），然后去二维码扫描（此时牵扯电脑权限所以会重启应用），然后这时候去应用设置，就会崩。。。

**Comment by xxmmllqqqqccqq** [comment]
全新安装，没有任何配置，点击应用设置就会崩。

**Comment by paradiseduo** [comment]
> 全新安装，没有任何配置，点击应用设置就会崩。

这么说我就了然了，等我找个电脑试试的

**Comment by paradiseduo** [comment]
release 1.7.1
