### ISSUE TITLE
下载后直接配置了地址，还是无法访问google Mac：10.14 端口没被占用

### ISSUE THREAD

**Issue by chanym888** [paradiseduo/ShadowsocksX-NG-R8#55]
**System and Shadowsocksx-NG-R8 version:**

- macOS 10.15.4 (19E287)
- Shadowsocksx-NG-R 1.6.2

**Expected behavior:**

**Actual behavior:**

(N/A for feature requests)

**Steps to reproduce:**

(N/A for feature requests)

**How often does this happen?**

(N/A for feature requests)

**ss-local.log**

Please upload the ss-local.log file here the file is in `~/Library/Logs`
1) Open 'Advanced Settings -> enable Verbose Mode'
2) Continue run `Shadowsocksx-NG-R` for 5 minutes
3) Upload the `~/Library/Logs/ss-local.log` here (with or without compress)

**Application log**

Open the `Console.app` and search `Shadowsocksx-NG-R8`
Copy paste the log here

**Crash Log**

If the app crashes and pop up a crash log, please copy and paste here

**Tips:**

- Always check for the latest update, some known bug has been fix in the latest release such as old version not support auth_aes_md5 auth_aes_sha1

- Beta version of macOS also may couse some problems

- ss-local compiled by macOS Sierra 10.12 not compatite with 10.11, some old release's ss-local are compiled using 10.12 will not work on 10.11, new release are try build in 10.10 to max fit the compatite

**Comment by chanym888** [comment]
macOS 10.15.5
Shadowsocksx-NG-R 1.7.0

**Comment by paradiseduo** [comment]
你说的地址是什么地址？
如果是订阅地址那么你选择订阅的节点可以使用吗？
如果订阅节点没有没问题，那么你需要检查一下ss-local进程有没有启动。

**Comment by chanym888** [comment]
1.是订阅地址。
2.可以使用，我在手机使用是没问题的。
3.
DXMdeMacBook-Pro-10% lsof -i tcp:1087
COMMAND    PID USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
Mate\x20T  555  dxm   18u  IPv4 0x1f91afdc7835cba3      0t0  TCP localhost:60574->localhost:cplscrambler-in (ESTABLISHED)
privoxy   9044  dxm    3u  IPv4 0x1f91afdc7866df23      0t0  TCP localhost:cplscrambler-in (LISTEN)
privoxy   9044  dxm    5u  IPv4 0x1f91afdc7847cba3      0t0  TCP localhost:cplscrambler-in->localhost:60574 (ESTABLISHED)
DXMdeMacBook-Pro-10%

**Comment by chanym888** [comment]
DXMdeMacBook-Pro-10% lsof -i tcp:1086
COMMAND   PID USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
ss-local 9627  dxm    8u  IPv4 0x1f91afdc77043f23      0t0  TCP localhost:cplscrambler-lg (LISTEN)

**Comment by paradiseduo** [comment]
看来sslocal启动了。
你这个是ssr的节点吗？另外可以直接在命令行里测一下代理好不好用。
先点击复制终端代理命令，粘贴到终端里，敲个回车，然后输入
curl cip.cc
看看是不是节点的IP地址

**Comment by chanym888** [comment]
DXMdeMacBook-Pro-10% curl cip.cc export http_proxy=http://127.0.0.1:1087;export https_proxy=http://127.0.0.1:1087;
IP	: 202.85.208.12
地址	: 中国  北京
运营商	: lenovo.com

数据二	: 北京市 | 易联时空(北京)科技有限公司(马连道街广外红莲南路欧园北欧印象4-2215号)

数据三	: 中国北京北京 | 联通

URL	: http://www.cip.cc/202.85.208.12
curl: (6) Could not resolve host: export
curl: (1) Protocol "http_proxy=http" not supported or disabled in libcurl
DXMdeMacBook-Pro-10%

**Comment by chanym888** [comment]
访问google时，出现了以下报错
500内部Privoxy错误
Privoxy在处理您的请求时遇到错误：

无法加载模板文件no-server-data或其包含的组件之一。

请与您的代理管理员联系。

如果您是代理管理员，请把所需文件放在(confdir)/templates目录中。(confdir)目录的位置在主Privoxy config文件中指定。（通常是Privoxy安装目录，或/etc/privoxy/）。

**Comment by chanym888** [comment]
500 Internal Privoxy Error
Privoxy encountered an error while processing your request:

Could not load template file no-server-data or one of its included components.

Please contact your proxy administrator.

If you are the proxy administrator, please put the required file(s)in the (confdir)/templates directory. The location of the (confdir) directory is specified in the main Privoxy config file. (It's typically the Privoxy install directory, or /etc/privoxy/).

**Comment by paradiseduo** [comment]
你命令打错了

**Comment by paradiseduo** [comment]
先执行终端代理命令

**Comment by chanym888** [comment]
命令：

**Comment by chanym888** [comment]
curl cip.cc export http_proxy=http://127.0.0.1:1087;export https_proxy=http://127.0.0.1:1087;
不是这样的吗？curl cip.cc export http_proxy=http://127.0.0.1:1087;export https_proxy=http://127.0.0.1:1087;

**Comment by chanym888** [comment]
DXMdeMacBook-Pro-10% curl cip.cc
IP	: 202.85.208.12
地址	: 中国  北京
运营商	: lenovo.com

数据二	: 北京市 | 易联时空(北京)科技有限公司(马连道街广外红莲南路欧园北欧印象4-2215号)

数据三	:

URL	: http://www.cip.cc/202.85.208.12
我是买的别人的地址，不知道他的IP是什么

**Comment by chanym888** [comment]
我自己ping测试，发现ip地址和curl cip.cc的不一样

**Comment by paradiseduo** [comment]
```bash
~ ❯ export http_proxy=http://127.0.0.1:1087;export https_proxy=http://127.0.0.1:1087;
~ ❯ curl cip.cc
IP	: 133.223.xxx.xxx
地址	: 日本  日本

数据二	: 日本

数据三	: 日本

URL	: http://www.cip.cc/133.223.xxx.xxx
```

**Comment by chanym888** [comment]
DXMdeMacBook-Pro-10% export http_proxy=http://127.0.0.1:1087;export https_proxy=http://127.0.0.1:1087;
DXMdeMacBook-Pro-10% curl cip.cc
<html>
<head>
 <title>500 Internal Privoxy Error</title>
 <link rel="shortcut icon" href="http://config.privoxy.org/error-favicon.ico" type="image/x-icon"></head>
<body>
<h1>500 Internal Privoxy Error</h1>
<p>Privoxy encountered an error while processing your request:</p>
<p><b>Could not load template file <code>connection-timeout</code> or one of its included components.</b></p>
<p>Please contact your proxy administrator.</p>
<p>If you are the proxy administrator, please put the required file(s)in the <code><i>(confdir)</i>/templates</code> directory.  The location of the <code><i>(confdir)</i></code> directory is specified in the main Privoxy <code>config</code> file.  (It's typically the Privoxy install directory, or <code>/etc/privoxy/</code>).</p>
</body>
</html>

**Comment by paradiseduo** [comment]
你的privoxy程序没有正确运行，使用socks5吧

**Comment by ibuler** [comment]
遇到同样的问题，1087端口没有启动, 版本 1.7.0(1) ，重启也不行

![image](https://user-images.githubusercontent.com/17382885/86347292-afdc8a00-bc90-11ea-984e-c700411626a3.png)

![image](https://user-images.githubusercontent.com/17382885/86347131-71df6600-bc90-11ea-9256-b3513d1f0ef5.png)
![image](https://user-images.githubusercontent.com/17382885/86347156-799f0a80-bc90-11ea-9239-e0fa8e7f1496.png)
![image](https://user-images.githubusercontent.com/17382885/86347250-9b988d00-bc90-11ea-838b-6f23491d6cf7.png)

**Comment by ibuler** [comment]
我的问题已解决， Privoxy无法正常启动，
手动启动时报 错：
```
dyld: Library not loaded: /usr/local/opt/pcre/lib/libpcre.1.dylib
  Referenced from: /Users/guang/Library/Application Support/ShadowsocksX-NG-R8/privoxy-3.0.28.static/./privoxy
  Reason: no suitable image found.  Did find:
	/usr/local/opt/pcre/lib/libpcre.1.dylib: code signature in (/usr/local/opt/pcre/lib/libpcre.1.dylib) not valid for use in process using Library Validation: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.
	/usr/local/opt/pcre/lib/libpcre.1.dylib: stat() failed with errno=1
[1]    4362 abort      ./privoxy
```

解决方法：
```
brew install privoxy
```
软连接到这里即可
```
cd ~/Library/Application\ Support/ShadowsocksX-NG-R8
rm -f privoxy
ln -s /usr/local/Cellar/privoxy/3.0.28/sbin/privoxy privoxy
```

**Comment by paradiseduo** [comment]
> 遇到同样的问题，1087端口没有启动, 版本 1.7.0(1) ，重启也不行

```
brew install privoxy
```
