### ISSUE TITLE
url scheme 不管用

### ISSUE THREAD

**Issue by Alexis374** [paradiseduo/ShadowsocksX-NG-R8#56]
**System and Shadowsocksx-NG-R8 version:**

- macOS 10.15.5
- Shadowsocksx-NG-R 1.7.0

**Expected behavior:**

**Actual behavior:**
chrome 浏览器中复制 ssr开头的链接，会有弹框提示要打开 ssr软件，但是点击确定没有反应；
在iterm中点击 ssr开头的链接，原来会自动导入服务器，但是现在也不行了
(N/A for feature requests)

**Steps to reproduce:**

(N/A for feature requests)

**How often does this happen?**

(N/A for feature requests)

**ss-local.log**

Please upload the ss-local.log file here the file is in `~/Library/Logs`
1) Open 'Advanced Settings -> enable Verbose Mode'
2) Continue run `Shadowsocksx-NG-R` for 5 minutes
3) Upload the `~/Library/Logs/ss-local.log` here (with or without compress)

**Application log**

Open the `Console.app` and search `Shadowsocksx-NG-R8`
Copy paste the log here

**Crash Log**

If the app crashes and pop up a crash log, please copy and paste here

**Tips:**

- Always check for the latest update, some known bug has been fix in the latest release such as old version not support auth_aes_md5 auth_aes_sha1

- Beta version of macOS also may couse some problems

- ss-local compiled by macOS Sierra 10.12 not compatite with 10.11, some old release's ss-local are compiled using 10.12 will not work on 10.11, new release are try build in 10.10 to max fit the compatite

**Comment by paradiseduo** [comment]
下个版本修复

**Comment by Alexis374** [comment]
> 下个版本修复

什么时候会发呢

**Comment by paradiseduo** [comment]
release 1.7.1
