### ISSUE TITLE
bug - 全局模式无法连接

### ISSUE THREAD

**Issue by wajncn** [paradiseduo/ShadowsocksX-NG-R8#58]
**System and Shadowsocksx-NG-R8 version:1.7.1 

- macOS 10.13.3
- Shadowsocksx-NG-R8 version:1.7.1 

全局模式无法连接.  打开Shadowsocksx特别慢. 很卡.  关闭打开特别卡.

**Comment by netbuilding** [comment]
我也是这样，全局模式无法连接。但手动模式填上服务器地址和端口就可以连上

**Comment by Luxiyu** [comment]
+1
macOS10.12.6 (16G2136)
MacBook Air (13-inch, 2017)
基本上只有pac模式可用

**Comment by dwciceage** [comment]
同问题 全局模式下 我是chrome 出现ERR_PROXY_CONNECTION_FAILED safari 浏览器则可以 正常访问

**Comment by paradiseduo** [comment]
> 同问题 全局模式下 我是chrome 出现ERR_PROXY_CONNECTION_FAILED safari 浏览器则可以 正常访问

Chrome浏览器请配合[SwitchyOmega](https://github.com/FelisCatus/SwitchyOmega)使用

**Comment by paradiseduo** [comment]
全局模式下请打开网络设置，截个图，然后告知一下用的什么浏览器，不然怎么给你定位问题？
![image](https://user-images.githubusercontent.com/14846965/89368718-caca7000-d70e-11ea-8043-cd479749b30a.png)

**Comment by paradiseduo** [comment]
> +1
> macOS10.12.6 (16G2136)
> MacBook Air (13-inch, 2017)
> 基本上只有pac模式可用

在开启软件的情况下，打开终端APP，依次输入：
```
> export http_proxy=http://127.0.0.1:1087;export https_proxy=http://127.0.0.1:1087;
> curl cip.cc
```
看看ip地址是否是代理服务器的IP，如果是，那么说明软件好使，浏览器有问题，Chrome内置代理规则很迷，建议配合[SwitchyOmega](https://github.com/FelisCatus/SwitchyOmega)使用。

**Comment by paradiseduo** [comment]
> 我也是这样，全局模式无法连接。但手动模式填上服务器地址和端口就可以连上

如果是Chrome浏览器，请配合[SwitchyOmega](https://github.com/FelisCatus/SwitchyOmega)使用

**Comment by Luxiyu** [comment]
> > +1 
> > macOS10.12.6（16G2136）
> > MacBook Air（13英寸，2017年）
> > 基本上只有pac模式可用
> 
> 在开启软件的情况下，打开终端APP，依次输入：
> 
> ```
> > export http_proxy=http://127.0.0.1:1087;export https_proxy=http://127.0.0.1:1087;
> > curl cip.cc
> ```
> 
> 看看ip地址是否是代理服务器的IP，如果是，那么说明软件好使，浏览器有问题，Chrome内置代理规则很[迷惑](https://github.com/FelisCatus/SwitchyOmega)，建议配合[SwitchyOmega](https://github.com/FelisCatus/SwitchyOmega)使用。

确定了是chrome的问题。就是SwitchyOmega用的很麻烦

**Comment by paradiseduo** [comment]
> > > +1
> > > macOS10.12.6（16G2136）
> > > MacBook Air（13英寸，2017年）
> > > 基本上只有pac模式可用
> > 
> > 
> > 在开启软件的情况下，打开终端APP，依次输入：
> > ```
> > > export http_proxy=http://127.0.0.1:1087;export https_proxy=http://127.0.0.1:1087;
> > > curl cip.cc
> > ```
> > 
> > 
> > 看看ip地址是否是代理服务器的IP，如果是，那么说明软件好使，浏览器有问题，Chrome内置代理规则很[迷惑](https://github.com/FelisCatus/SwitchyOmega)，建议配合[SwitchyOmega](https://github.com/FelisCatus/SwitchyOmega)使用。
> 
> 确定了是chrome的问题。就是SwitchyOmega用的很麻烦

用习惯了还可以啊，就是一开始配置麻烦些，配置好之后切换代理很方便
