### ISSUE TITLE
macOS 10.15.6 无法上网

### ISSUE THREAD

**Issue by forJrking** [paradiseduo/ShadowsocksX-NG-R8#60]
**System and Shadowsocksx-NG-R8 version:**

- macOS 10.15.6 (19G73)
- Shadowsocksx-NG-R 1.7.1

**Application log**

Aug 17 19:40:28 Forjrking-MacPro com.apple.xpc.launchd[1] (com.apple.xpc.launchd.domain.pid.proxy_conf_help.12942): Failed to bootstrap path: path = /Library/Application Support/ShadowsocksX-NG-R8/proxy_conf_helper, error = 2: No such file or directory
Aug 17 19:43:20 Forjrking-MacPro com.apple.xpc.launchd[1] (com.apple.xpc.launchd.domain.pid.proxy_conf_help.13065): Failed to bootstrap path: path = /Library/Application Support/ShadowsocksX-NG-R8/proxy_conf_helper, error = 2: No such file or directory
Aug 17 19:43:20 Forjrking-MacPro com.apple.xpc.launchd[1] (com.apple.xpc.launchd.domain.pid.proxy_conf_help.13066): Failed to bootstrap path: path = /Library/Application Support/ShadowsocksX-NG-R8/proxy_conf_helper, error = 2: No such file or directory
**Crash Log**

**Comment by paradiseduo** [comment]
先下载：
[proxy_conf_helper.zip](https://github.com/paradiseduo/ShadowsocksX-NG-R8/files/5087713/proxy_conf_helper.zip)
然后自己解压到该路径下：
```
/Library/Application Support/ShadowsocksX-NG-R8/
```

如果报恶意软件的错误，可以执行该命令：
```
sudo xattr -rd com.apple.quarantine /Library/Application\ Support/ShadowsocksX-NG-R8/proxy_conf_helper
```

**Comment by kingsd041** [comment]
@paradiseduo  
10.15.6 (19G2021) 
ShadowsocksX-NG-R8 版本1.7.1 (1)

还是存在相同的问题，从新安装之后，默认的`/Library/Application Support/ShadowsocksX-NG-R8/` 目录下其实已经有该文件，但还是提示上面的错误

不知道是不是因为这个错误，导致开启之后无法访问google等网络，但更像订阅，服务器测速均正常

logs:
```
Aug 24 21:07:42 MacBook-Pro com.apple.xpc.launchd[1] (com.apple.xpc.launchd.domain.pid.proxy_conf_help.8047): Failed to bootstrap path: path = /Library/Application Support/ShadowsocksX-NG-R8/proxy_conf_helper, error = 2: No such file or directory
Aug 24 21:07:42 MacBook-Pro com.apple.xpc.launchd[1] (com.apple.xpc.launchd.domain.pid.proxy_conf_help.8048): Failed to bootstrap path: path = /Library/Application Support/ShadowsocksX-NG-R8/proxy_conf_helper, error = 2: No such file or directory
```

```
ll /Library/Application\ Support/ShadowsocksX-NG-R8/proxy_conf_helper
-rwsr-sr-x@ 1 root  admin    53K  8 24 21:06 /Library/Application Support/ShadowsocksX-NG-R8/proxy_conf_helper
```

**Comment by paradiseduo** [comment]
这个问题我再研究研究，这一块新系统总出问题，打算重写了。

**Comment by kingsd041** [comment]
非常感谢

**Comment by llk2yq** [comment]
遇到了相同的问题，测速正常，但是不能上404网站。

**Comment by paradiseduo** [comment]
> 遇到了相同的问题，测速正常，但是不能上404网站。

测速正常是科学上网的必要不充分条件。
目前测速的机制仅仅是判断与服务器建立tcp链接的速度，能不能科学上网取决于很多因素。

**Comment by paradiseduo** [comment]
建议使用clashX，最新版已支持SSR，本项目由于____已终止维护。
