### ISSUE TITLE
命令行如何执行'更新PAC名单'

### ISSUE THREAD

**Issue by CodeFancier** [paradiseduo/ShadowsocksX-NG-R8#62]
**System and Shadowsocksx-NG-R8 version:**

- macOS 10.15.6 (19G73)
- Shadowsocksx-NG-R 1.7.1

### 问题描述：
1.写了个脚本，用于自定义规则写入到/Users/xx/.ShadowsocksX-NG/user-rule.txt
2.但是重启SSR后，/Users/xx/.ShadowsocksX-NG/gfwlist.js中未包含自定义规则
3.尝试了从APP界面-应用设置-规则设置-更新PAC名单，规则成功写入gfwlist.js中

### 需求：
1.从命令行执行ShadowsocksX-NG-R8- ’**更新PAC名单**‘功能

**Comment by paradiseduo** [comment]
发生这个问题的原因找到了，程序只有在点击更新PAC的时候才会重新读取user-rule.txt，等我改改，改成判断user-rule.txt发生变化就去重新读取。但是也需要重启软件或者更换一次模式才会刷新。

另外之前做了使用命令操作软件的版本，因为执行异步任务有问题，所以没有放出来，也没再继续开发。

**Comment by CodeFancier** [comment]
感谢作者回复，监听user-rule.txt变化重新读取是很棒的。

考虑到我的脚本，也许只需满足重启时重新读取ur.txt即可，我在脚本最后一行重启应用即可。

另外，命令行操作后续会开放吗？

**Comment by paradiseduo** [comment]
> 感谢作者回复，监听user-rule.txt变化重新读取是很棒的。
> 
> 考虑到我的脚本，也许只需满足重启时重新读取ur.txt即可，我在脚本最后一行重启应用即可。
> 
> 另外，命令行操作后续会开放吗？

可能会出一个不开源的Pro版本吧。
