### ISSUE TITLE
请问能不能绕过局域网和中国大陆地址？

### ISSUE THREAD

**Issue by reaCodes** [paradiseduo/ShadowsocksX-NG-R8#64]
**System and Shadowsocksx-NG-R8 version:**

- macOS 10.15.6 (19G2021)
- Shadowsocksx-NG-R 1.7.2

**Comment by reaCodes** [comment]
不好意思，我好想找到这个功能了，这个叫白名单模式，请问这个白名单是怎么更新的？

**Comment by paradiseduo** [comment]
![image](https://user-images.githubusercontent.com/14846965/92341241-b0115f80-f0ef-11ea-9be6-8ec715c446b1.png)
