### ISSUE TITLE
sock5设置无效

### ISSUE THREAD

**Issue by TomYule** [paradiseduo/ShadowsocksX-NG-R8#66]
**System and Shadowsocksx-NG-R8 version:**
sock5设置无效
- macOS 10.15.6 (19G2021)
- Shadowsocksx-NG-R 1.7.2

**Expected behavior:**
安装 telegram
设置代理
127.0.0.1
1086
无法登陆
软件用 https://github.com/yanue/V2rayU
设置sock5 可用正常登陆

**Actual behavior:**

(N/A for feature requests)

**Steps to reproduce:**

(N/A for feature requests)

**How often does this happen?**

(N/A for feature requests)

**ss-local.log**

Please upload the ss-local.log file here the file is in `~/Library/Logs`
1) Open 'Advanced Settings -> enable Verbose Mode'
2) Continue run `Shadowsocksx-NG-R` for 5 minutes
3) Upload the `~/Library/Logs/ss-local.log` here (with or without compress)

**Application log**

Open the `Console.app` and search `Shadowsocksx-NG-R8`
Copy paste the log here

**Crash Log**

If the app crashes and pop up a crash log, please copy and paste here

**Tips:**

- Always check for the latest update, some known bug has been fix in the latest release such as old version not support auth_aes_md5 auth_aes_sha1

- Beta version of macOS also may couse some problems

- ss-local compiled by macOS Sierra 10.12 not compatite with 10.11, some old release's ss-local are compiled using 10.12 will not work on 10.11, new release are try build in 10.10 to max fit the compatite

**Comment by paradiseduo** [comment]
你需要查一下开启SSR之后1086端口的开启状况，以及查看是否有其他软件占用了该端口。
我没记错的话V2rayU好像也是默认开启1086端口的

**Comment by TomYule** [comment]
> 你需要查一下开启SSR之后1086端口的开启状况，以及查看是否有其他软件占用了该端口。
> 我没记错的话V2rayU好像也是默认开启1086端口的

1086 没有被占用;
就第一步 登录 发送验证码 一直失败 
用 V2rayU  登录 成功后 关闭 V2rayU  打开Shadowsocksx 后面 重新打开 软件  telegram 能上网

**Comment by TomYule** [comment]
呃 这个 BUG 不解决了么

**Comment by paradiseduo** [comment]
> 呃 这个 BUG 不解决了么

这个问题我没有复现出来，代理配置好以后TG的任何请求都畅通无阻：
![image](https://user-images.githubusercontent.com/14846965/93739256-76297880-fc1a-11ea-970a-394ca3b571db.png)
![image](https://user-images.githubusercontent.com/14846965/93739310-935e4700-fc1a-11ea-9e4e-7d5a42994cc3.png)
![image](https://user-images.githubusercontent.com/14846965/93739169-36fb2780-fc1a-11ea-802b-64bb8eccbb8a.png)
![image](https://user-images.githubusercontent.com/14846965/93739151-2b0f6580-fc1a-11ea-8365-04cdd021bfec.png)

**Comment by TomYule** [comment]
好吧 这个是个神奇的BUG
