### ISSUE TITLE
用户PAC规则不生效

### ISSUE THREAD

**Issue by xiaoleigithub** [paradiseduo/ShadowsocksX-NG-R8#67]
**System and Shadowsocksx-NG-R8 version:**

- macOS 10.15.6 (19G2021)
- Shadowsocksx-NG-R 1.7.2

用户PAC规则不生效，确认一下写法是这样的吗？
||ipchaxun.com/
@@*.ip138.com/

||代表走代理
@@代表直连
··········································

![image](https://user-images.githubusercontent.com/46390738/93410923-8e249380-f8cc-11ea-86b5-b2d0224829ce.png)
![image](https://user-images.githubusercontent.com/46390738/93410934-92e94780-f8cc-11ea-9786-10d89cab2d32.png)
![image](https://user-images.githubusercontent.com/46390738/93410941-97adfb80-f8cc-11ea-9a0f-f685a0fbed85.png)

**Comment by paradiseduo** [comment]
直连：
```
@@||ip138.com
```
走代理：
```
||ipip.net
```

另外这里我测了一下，如果更新过快可能会出现规则来不及刷新的情况，可以通过切换一下模式解决，下个版本会优化这个地方.

**Comment by xiaoleigithub** [comment]
好的呢，感谢！
