### ISSUE TITLE
大佬，要不要考虑下把V2ray合到新版本中

### ISSUE THREAD

**Issue by Sam-Caesarmat** [paradiseduo/ShadowsocksX-NG-R8#8]
参考 https://github.com/yanue/V2rayU/releases

**Comment by paradiseduo** [comment]
目前还不考虑，毕竟V2ray已经有成熟的客户端了，增加太多的插件只会增加安装包的体积，对于不走代理直接下载软件的用户来说，太大的安装包仅靠10+kb的下载速度要下很久(｡•ˇ‸ˇ•｡)

**Comment by Sam-Caesarmat** [comment]
> 目前还不考虑，毕竟V2ray已经有成熟的客户端了，增加太多的插件只会增加安装包的体积，对于不走代理直接下载软件的用户来说，太大的安装包仅靠10+kb的下载速度要下很久(｡•ˇ‸ˇ•｡)

😁
