### ISSUE TITLE
TCP:1087 port couldn't be opened under Global mode in the latest v1.5.9 version

### ISSUE THREAD

**Issue by 171621** [paradiseduo/ShadowsocksX-NG-R8#9]
System: macOS Catalina 10.15.4 (19E266)
App version: v1.5.9 latest release

Problem: From the Network Utility app, it shows the TCP:1087 port is not open when switching to Global Mode:

>Port Scanning host: 127.0.0.1

	 Open TCP Port: 	1086   		cplscrambler-lg

Compared with v1.5.7 version, certain TCP port can be opened automatically once Global Mode is enabled:

>Port Scanning host: 127.0.0.1

	 Open TCP Port: 	1086   		cplscrambler-lg
	 Open TCP Port: 	1087   		cplscrambler-in

Not sure what caused the issue, just wondering if you could help take a look on this issue? Many thanks!

**Comment by autoreleasepools** [comment]
I also encountered this problem.
App version: v1.5.9 latest release
macOS10.13.6 + Global Mode + Chrome doesn't work
macOS10.13.6 + Global Mode + Safari is OK

**Comment by paradiseduo** [comment]
please show me log:
```
cat ~/Library/Logs/privoxy.log
```

**Comment by paradiseduo** [comment]
> I also encountered this problem.
> App version: v1.5.9 latest release
> macOS10.13.6 + Global Mode + Chrome doesn't work
> macOS10.13.6 + Global Mode + Safari is OK

please show me log:
```
cat ~/Library/Logs/privoxy.log
```

and you can try delete support file and reopen APP:
```
rm -rf ~/Library/Application\ Support/ShadowsocksX-NG-R8
```

**Comment by wzdnzd** [comment]
It may be caused by the lack of libpcre.1.dylib

**Comment by 171621** [comment]
I have deleted all the related folders and files from the previous versions and fresh installed the v1.5.9 one, and here is the log I've got:

> localhost:~ user$ cat ~/Library/Logs/privoxy.log
2020-04-07 20:40:24.189 0010b444 Info: Privoxy version 3.0.26
2020-04-07 20:40:24.292 0010b444 Info: Program name: /Users/user/Library/Application Support/ShadowsocksX-NG-R8/privoxy
2020-04-07 20:40:30.516 001084d2 Info: Privoxy version 3.0.26
2020-04-07 20:40:30.520 001084d2 Info: Program name: /Users/user/Library/Application Support/ShadowsocksX-NG-R8/privoxy
2020-04-07 20:44:00.866 00105903 Info: Privoxy version 3.0.26
2020-04-07 20:44:00.866 00105903 Info: Program name: /Users/user/Library/Application Support/ShadowsocksX-NG-R8/privoxy
dyld: Library not loaded: /usr/local/opt/pcre/lib/libpcre.1.dylib
  Referenced from: /Users/user/Library/Application Support/ShadowsocksX-NG-R8/privoxy
  Reason: image not found
dyld: Library not loaded: /usr/local/opt/pcre/lib/libpcre.1.dylib
  Referenced from: /Users/user/Library/Application Support/ShadowsocksX-NG-R8/privoxy
  Reason: image not found
dyld: Library not loaded: /usr/local/opt/pcre/lib/libpcre.1.dylib
  Referenced from: /Users/user/Library/Application Support/ShadowsocksX-NG-R8/privoxy
  Reason: image not found
dyld: Library not loaded: /usr/local/opt/pcre/lib/libpcre.1.dylib
  Referenced from: /Users/user/Library/Application Support/ShadowsocksX-NG-R8/privoxy
  Reason: image not found
dyld: Library not loaded: /usr/local/opt/pcre/lib/libpcre.1.dylib
  Referenced from: /Users/user/Library/Application Support/ShadowsocksX-NG-R8/privoxy
  Reason: image not found
dyld: Library not loaded: /usr/local/opt/pcre/lib/libpcre.1.dylib
  Referenced from: /Users/user/Library/Application Support/ShadowsocksX-NG-R8/privoxy
  Reason: image not found

It seems indeed that the libpcre.1.dylib file is missing. And then I realized that Privoxy version shown in the log is still 3.0.26, even though it should be upgraded to 3.0.28, so I manually deleted the "~/Library/Application\ Support/ShadowsocksX-NG-R8" folder and then relaunched the app, in the log file it only shows the libpcre.1.dylib file problem, no more Privoxy version info is displayed.

**Comment by paradiseduo** [comment]
> I have deleted all the related folders and files from the previous versions and fresh installed the v1.5.9 one, and here is the log I've got:
> 
> > localhost:~ user$ cat ~/Library/Logs/privoxy.log
> > 2020-04-07 20:40:24.189 0010b444 Info: Privoxy version 3.0.26
> > 2020-04-07 20:40:24.292 0010b444 Info: Program name: /Users/user/Library/Application Support/ShadowsocksX-NG-R8/privoxy
> > 2020-04-07 20:40:30.516 001084d2 Info: Privoxy version 3.0.26
> > 2020-04-07 20:40:30.520 001084d2 Info: Program name: /Users/user/Library/Application Support/ShadowsocksX-NG-R8/privoxy
> > 2020-04-07 20:44:00.866 00105903 Info: Privoxy version 3.0.26
> > 2020-04-07 20:44:00.866 00105903 Info: Program name: /Users/user/Library/Application Support/ShadowsocksX-NG-R8/privoxy
> > dyld: Library not loaded: /usr/local/opt/pcre/lib/libpcre.1.dylib
> > Referenced from: /Users/user/Library/Application Support/ShadowsocksX-NG-R8/privoxy
> > Reason: image not found
> > dyld: Library not loaded: /usr/local/opt/pcre/lib/libpcre.1.dylib
> > Referenced from: /Users/user/Library/Application Support/ShadowsocksX-NG-R8/privoxy
> > Reason: image not found
> > dyld: Library not loaded: /usr/local/opt/pcre/lib/libpcre.1.dylib
> > Referenced from: /Users/user/Library/Application Support/ShadowsocksX-NG-R8/privoxy
> > Reason: image not found
> > dyld: Library not loaded: /usr/local/opt/pcre/lib/libpcre.1.dylib
> > Referenced from: /Users/user/Library/Application Support/ShadowsocksX-NG-R8/privoxy
> > Reason: image not found
> > dyld: Library not loaded: /usr/local/opt/pcre/lib/libpcre.1.dylib
> > Referenced from: /Users/user/Library/Application Support/ShadowsocksX-NG-R8/privoxy
> > Reason: image not found
> > dyld: Library not loaded: /usr/local/opt/pcre/lib/libpcre.1.dylib
> > Referenced from: /Users/user/Library/Application Support/ShadowsocksX-NG-R8/privoxy
> > Reason: image not found
> 
> It seems indeed that the libpcre.1.dylib file is missing. And then I realized that Privoxy version shown in the log is still 3.0.26, even though it should be upgraded to 3.0.28, so I manually deleted the "~/Library/Application\ Support/ShadowsocksX-NG-R8" folder and then relaunched the app, in the log file it only shows the libpcre.1.dylib file problem, no more Privoxy version info is displayed. BTW I was using chacha20-ietf, auth_aes128_sha1 and tls1.2_ticket_auth within the configurations, just in case if you are wondering.

maybe you can try this
```
brew install privoxy
```
homebrew will install missing lib
![image](https://user-images.githubusercontent.com/14846965/78737039-311dcc80-7981-11ea-87ad-b1c818995dc1.png)

**Comment by 171621** [comment]
> > I have deleted all the related folders and files from the previous versions and fresh installed the v1.5.9 one, and here is the log I've got:
> > > localhost:~ user$ cat ~/Library/Logs/privoxy.log
> > > 2020-04-07 20:40:24.189 0010b444 Info: Privoxy version 3.0.26
> > > 2020-04-07 20:40:24.292 0010b444 Info: Program name: /Users/user/Library/Application Support/ShadowsocksX-NG-R8/privoxy
> > > 2020-04-07 20:40:30.516 001084d2 Info: Privoxy version 3.0.26
> > > 2020-04-07 20:40:30.520 001084d2 Info: Program name: /Users/user/Library/Application Support/ShadowsocksX-NG-R8/privoxy
> > > 2020-04-07 20:44:00.866 00105903 Info: Privoxy version 3.0.26
> > > 2020-04-07 20:44:00.866 00105903 Info: Program name: /Users/user/Library/Application Support/ShadowsocksX-NG-R8/privoxy
> > > dyld: Library not loaded: /usr/local/opt/pcre/lib/libpcre.1.dylib
> > > Referenced from: /Users/user/Library/Application Support/ShadowsocksX-NG-R8/privoxy
> > > Reason: image not found
> > > dyld: Library not loaded: /usr/local/opt/pcre/lib/libpcre.1.dylib
> > > Referenced from: /Users/user/Library/Application Support/ShadowsocksX-NG-R8/privoxy
> > > Reason: image not found
> > > dyld: Library not loaded: /usr/local/opt/pcre/lib/libpcre.1.dylib
> > > Referenced from: /Users/user/Library/Application Support/ShadowsocksX-NG-R8/privoxy
> > > Reason: image not found
> > > dyld: Library not loaded: /usr/local/opt/pcre/lib/libpcre.1.dylib
> > > Referenced from: /Users/user/Library/Application Support/ShadowsocksX-NG-R8/privoxy
> > > Reason: image not found
> > > dyld: Library not loaded: /usr/local/opt/pcre/lib/libpcre.1.dylib
> > > Referenced from: /Users/user/Library/Application Support/ShadowsocksX-NG-R8/privoxy
> > > Reason: image not found
> > > dyld: Library not loaded: /usr/local/opt/pcre/lib/libpcre.1.dylib
> > > Referenced from: /Users/user/Library/Application Support/ShadowsocksX-NG-R8/privoxy
> > > Reason: image not found
> > 
> > 
> > It seems indeed that the libpcre.1.dylib file is missing. And then I realized that Privoxy version shown in the log is still 3.0.26, even though it should be upgraded to 3.0.28, so I manually deleted the "~/Library/Application\ Support/ShadowsocksX-NG-R8" folder and then relaunched the app, in the log file it only shows the libpcre.1.dylib file problem, no more Privoxy version info is displayed. 
> 
> maybe you can try this
> 
> ```
> brew install privoxy
> ```
> 
> homebrew will install missing lib
> ![image](https://user-images.githubusercontent.com/14846965/78737039-311dcc80-7981-11ea-87ad-b1c818995dc1.png)


Installing privoxy via brew successfully solved the issue, it's working fine now. Many thanks for the instruction!
